### ISSUE TITLE
Videos from youtube/googlevideo.com not loading via HTTPS

### ISSUE THREAD

**Issue by kull0rk3x** [dlundquist/sniproxy#113]
Hi,

sniproxy fails to load youtube videos via HTTPS for me. It works like a charm for normal webpages (including the youtube.com website), but not for the videos.
They take a long time (up to 20 seconds) to load, then respond with an 502 Bad Gateway error.
Loading youtube without SSL works just fine. Loading it with SSL but without sniproxy works fine, too.

My config has barely anything in it:

```
user daemon
pidfile /var/run/sniproxy.pid

error_log {
    filename /var/log/sniproxy.log
    priority notice
}

listen 80 {
    proto http
    table http_hosts
}

listen 443 {
    proto tls
    table https_hosts
}

table http_hosts {
    .*      *
}

table https_hosts {
    .*  *
}
```

Nothing of interest is logged into the log file or to STDOUT when I run it with -f.

**Comment by palxex** [comment]
Did you find any solution? Just fall in same problem.

**Comment by KalelCooper** [comment]
I have same issue
