### ISSUE TITLE
Outgoing connection to server using the same interface/address as incoming request from client

### ISSUE THREAD

**Issue by robotiv** [dlundquist/sniproxy#135]
Hi Dustin,

Great project, I've been following it for quite some time.

I was wondering if it would be possible to add an option to have incoming client requests serviced out using the same interface/address when going to the specified backend server in the table.

As an example, my server has 5 IP addresses and sniproxy listens on all of them and happily processes the client requests regardless of IP used. The problem is that the outgoing connections to the backend servers in the table (or the specified host when using *) is done through the default interface because of the routing rules on the machine. Would it be possible to have an option in sniproxy to have requests to the servers be done on the same interface they came in? I understand that this might be possible to do with some iproute2 commands but it would be much nicer if I could specify it as an option.

If this is already possible, I must have missed it. Thanks in advance.

**Comment by Copytalky** [comment]
I've been trying to get this to work and cannot. I manage to get sniproxy to 'bind' but it appears to still traffic everything through the linux kernels default gateway.
I have the following scenario:
-two different public IP addresses.
- binding them in both these configurations causes no difference in results:

--------------------------------------------------------------------------------------------------------------------------
auto eth0
iface eth0 inet static
        hwaddress ether 00:00:d1:d0:1a:cc
        address 204.xxx.xxx.2
        netmask 255.255.255.0
        gateway 204.xxx.xxx.1
        dns-nameservers 8.8.8.8 8.8.4.4
auto eth0:0
iface eth0:0 inet static
        address 104.xxx.xxx.3
        netmask 255.255.254.0
        gateway 104.xxx.xxx.1
        dns-nameservers 8.8.8.8 8.8.4.4

OR with this style which puts all virtual IP's under eth0 and no sub virtuals:

auto eth0
iface eth0 inet static
        hwaddress ether 00:00:d1:d0:1a:cc
        address 204.xxx.xxx.2
        netmask 255.255.255.0
        gateway 204.xxx.xxx.1
        dns-nameservers 8.8.8.8 8.8.4.4
auto eth0
iface eth0 inet static
        address 104.xxx.xxx.3
        netmask 255.255.254.0
        gateway 104.xxx.xxx.1
        dns-nameservers 8.8.8.8 8.8.4.4

--------------------------------------------------------------------------------------------------------------------------
sniproxy appears to load OK with no errors in the error log with this configuration.

however when I use the following sniproxy conf file and test going to a webpage that shows public IP's. It always shows the 204.xxx.xxx.2 IP even though the request originated to 104.xxx.xxx.3 IP. the systems default gateway is the 204.xxx.xxx.1 gateway. It appears sniproxy is utilizing the systems default gateway still and not the SOURCE IP I have provided in sniproxy conf:

--------------------------------------------------------------------------------------------------------------------------
user daemon

error_log {
    filename /tmp/sniproxy_error.log
    priority debug
}

pidfile /var/tmp/sniproxy.pid
listen 204.xxx.xxx.2:80 {
    proto http
        source 204.xxx.xxx.2
access_log {
        filename /tmp/sniproxy_access.log
}

}
listen 204.xxx.xxx.2:443 {
    proto tls
        source 204.xxx.xxx.2
access_log {
        filename /tmp/sniproxy_access.log
}

}

listen 104.xxx.xxx.3:80 {
    proto http
        source 104.xxx.xxx.3
access_log {
        filename /tmp/sniproxy_access.log
}

}
listen 104.xxx.xxx.3:443 {
    proto tls
        source 104.xxx.xxx.3
access_log {
        filename /tmp/sniproxy_access.log
}
}

table {
    .*\\.* *

}

--------------------------------------------------------------------------------------------------------------------------


I have also enabled this sysctl function: net.ipv4.ip_nonlocal_bind = 1 as noted by users of HAProxy that had the same issue of HAProxy not binding. I thought it may work as a resolution for sniproxy but has not.

Any ideas?
