### ISSUE TITLE
Confused about a listening port with sniproxy

### ISSUE THREAD

**Issue by hdavy2002** [dlundquist/sniproxy#147]
Folks, 
I am wondering what udp port is this for SNIProxy 0 0.0.0.0:56778?? Below is my netstat -tunlp output. I understand it is a dynamic port. Just curious. I assume sniproxy uses that to communicate something.

Thanks in advance

tcp        0      0 192.168.0.22:443          0.0.0.0:*                   LISTEN      520/sniproxy
tcp        0      0 192.168.0.22:2222         0.0.0.0:*                   LISTEN      734/sshd
tcp        0      0 192.168.0.22:80           0.0.0.0:*                   LISTEN      520/sniproxy
tcp        0      0 192.168.0.22:81           0.0.0.0:*                   LISTEN      608/perl
tcp        0      0 192.168.0.22:53           0.0.0.0:*                   LISTEN      707/unbound
udp        0      0 192.168.0.22:53           0.0.0.0:*                               707/unbound
udp        0      0 0.0.0.0:56778               0.0.0.0:*                               520/sniproxy

**Comment by dlundquist** [comment]
The DNS resolver in libudns is the only UDP socket in SNIProxy. Please see
the note in the README recommending running a local caching resolver.

-Dustin
