### ISSUE TITLE
Amazon Fire TV Stick Apps section not working

### ISSUE THREAD

**Issue by andlcool** [dlundquist/sniproxy#148]
Hi,

I managed to get Amazon Instant Video and Netflix streaming. However, apps cannot be viewed. When i try to access the apps section on the Fire Stick, it says apps not found. None of apps from the appstore are shown except for those that are already installed. I checked the error log and it shows that:

Request from [my home connection ip] did not include a hostname
Unable to parse request from [my home connection ip] parse_packet returned -5

On a side note, the same error message is also showed when i try to search using the the search bar on the amazon app on my android phone. The rest of the app such as my cart and other product page is working fine.

Anyone has any idea?

**Comment by janeczku** [comment]
Why would you even want to proxy the connection to the Amazon app store ?
The error log indicates that the client (whatever makes the connection to the app store) is missing SNI support and therefore does not send the hostname server in the SSL handshake.
While sniproxy relies on SNI being enabled on the client side there's a dirty workaround for situations such as yours:

In the sniproxy.conf, enable the fallback keyword and point it to the Amazon app store server hostname:

> fallback appstore.hostname.amazon.com:443

Be advised that by doing so all unparsable requests will be unconditionally tunneled to the app store server.
