### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by pacmac** [dlundquist/sniproxy#153]
Hi;

I've been using sniproxy successfully for several months, and are now trying to configure a service that uses ssl and it is failing with handshaking / wrong version errors.

If I connect directly, then the ssl connection is successful, however connecting vis sniproxy the connection always fails:
via sniproxy (fail)
-
    echo | openssl s_client -host movies.netflix.com -port 443
    CONNECTED(00000003)
    140223388886688:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert  handshake failure:s23_clnt.c:770:

directly (success)
-
    root@HOMESERV:~# echo | openssl s_client -host movies.netflix.com -port 443
    CONNECTED(00000003)
    depth=2 C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 1999 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G3

Any suggestions on the cause and possible fix ?

Many Thanks

**Comment by pacmac** [comment]
I now believe this to be a client issue with Python, the following code snippet shows the connection and executing the script results in different connection errors (handshake, wrong version) depending upon which version of ssl is used:

    #!/usr/bin/python
    import requests
    import ssl
    from requests.adapters import HTTPAdapter
    try:
      from requests.packages.urllib3.poolmanager import PoolManager
    except:
      from urllib3.poolmanager import PoolManager
      
    class SSLAdapter(HTTPAdapter):
      def init_poolmanager(self, connections, maxsize, block=False):
        ssl_version=ssl.PROTOCOL_TLSv1
        #ssl_version=ssl.PROTOCOL_SSLv23
        #ssl_version=ssl.PROTOCOL_SSLv3
        assert_hostname = 'netflix.com'
        self.poolmanager = PoolManager(num_pools=connections,maxsize=maxsize,block=block,ssl_version=ssl_version,assert_hostname=assert_hostname)
    
    def newSession():
      s = requests.Session()
      s.mount('https://', SSLAdapter())
      s.headers.update({'User-Agent': 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.6 Safari/537.36'})
      return s
    
    urlMain = "https://www.netflix.com"
    session = None
    session = newSession()
    session.get(urlMain, verify=False).text

This results in:

    requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure

Looking at the logs from the sniproxy server, you can see that the servername is omitted None[];

    2015-02-22 08:25:23 000.000.73.222:59288 -> 000.00.77.145:443 -> NONE [] 0/0 bytes tx 0/0 bytes rx 20.179 seconds

Do you happen to know how can I modify the script so that it sends the servername with the request ?

**Comment by pacmac** [comment]
OK, this is a problem with Python < 2.7.9 which does not support SNI.

The fix is here: https://urllib3.readthedocs.org/en/latest/contrib.html

**Comment by gun1x** [comment]
I am getting the same error for `bbc.co.uk` and `bbc.com`:

bash-5.0# curl -kvL https://bbc.co.uk
*   Trying 10.10.10.10:443...
* TCP_NODELAY set
* Connected to bbc.co.uk (10.10.10.10) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=GB; ST=London; L=London; O=British Broadcasting Corporation; CN=www.bbc.com
*  start date: May 28 12:30:02 2019 GMT
*  expire date: Aug  5 09:36:04 2020 GMT
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign RSA OV SSL CA 2018
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5589c2a23120)
> GET / HTTP/2
> Host: bbc.co.uk
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 301 
< server: Varnish
< retry-after: 0
< accept-ranges: bytes
< date: Fri, 18 Oct 2019 14:09:30 GMT
< via: 1.1 varnish
< x-served-by: cache-lcy19220-LCY
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1571407770.236722,VS0,VE0
< nel: {'report_to':'default','max_age': 86400,'include_subdomains':true,'failure_fraction':0.5}
< report-to: {'group':'default','max_age':86400,'endpoints':[ {'url':'https://europe-west1-bbc-otg-traf-mgr-bq-prod-4591.cloudfunctions.net/report-endpoint','priority':1} ],'include_subdomains':true}
< strict-transport-security: max-age=86400
< cache-control: public,max-age=604800,stale-while-revalidate=3600,stale-if-error=3600
< location: https://www.bbc.co.uk/
< content-length: 0
< 
* Connection #0 to host bbc.co.uk left intact
* Issue another request to this URL: 'https://www.bbc.co.uk/'
*   Trying 10.10.10.10:443...
* TCP_NODELAY set
* Connected to www.bbc.co.uk (10.10.10.10) port 443 (#1)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, handshake failure (552):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* Closing connection 1
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
