### ISSUE TITLE
Question : Can it be made multi process to take benefits of multi core machines

### ISSUE THREAD

**Issue by balyanrobin** [dlundquist/sniproxy#155]
Hi Gurus,

Is it possible to make it multi process to take benefits of multi core machines. I am really not a C programmer, guidance would be much appreciated.

Thanks,
Robin

**Comment by dlundquist** [comment]
It would be possible, but would add significantly the the complexity. The simplest approach, would be to split listeners between multiple SNIProxy instances. If a single listener was the bottle neck, one could modify SNIProxy to fork off several works after creating the listening socket, all of these worker processes with run the main event look and `accept()` the next available connection on the listening socket. This would add to the complexity of gathering statistics and reloading configurations since, but if these features were not required it would be a good option for a single high performance installation. Beyond this, it becomes an increasing trade off.

That being said, I'm curious how much traffic your pushing so this is an issue. I would expect file descriptor limits to be the limiting factor before single threaded performance unless something is going wrong. Another simple option would be to run N instances of SNIProxy each listening on a different IP, and then use DNS round-robin, or a stateful firewall load balance to distribute incoming connections across these instances.

**Comment by balyanrobin** [comment]
Hello dlundquist,

Thanks for the response and yes i agree SniProxy performs really well. But these machines are really big  and 16 cores are normal for any decent deployment. Moreover the plenty of memory and multi Gb network capabilities. As far as file descriptors are concerned, my useless is big files transfer and once the connection is established, it remain active for some time. But these are not the only concerns i have.
If i front face multiple instances of SNIProxy, i need to waste almost double the resources (Load balancer like HAProxy) in terms of CPU, memory and the delay induced. And the biggest drawback is loosing the client IP in TLS requests. The project i am working on need this IP for sure to build enforcements, and if i am not wrong, most of the systems software build around SNIProxy would need it.

I think instead of multithreaded, we need master-slave architecture like nginx and HAProxy does. and similar approach is used by SNIProxy for daemon/background mode. That way we can preserve the reload functionality, i hope. I don't know how to change the code, with some help i would like to change and try that.

Please suggest what do you think.

Thanks,
Robin

**Comment by dlundquist** [comment]
@balyanrobin have you profiled the existing deployment? Do you know what percentage of CPU time is spent servicing system calls verses in user space? Have you seen anything that may point to what your current bottle neck is? I've done some limiting profiling using the test suite (e.g. `cd tests; ./functional_test valgrind --tool=callgrind`) and user space time is pretty well distributed, with the majority of it spend formatting access log messages.

You might take a look at `tests/bench_sniproxy` as a starting place for a test on your existing systems. For any meaningful measurements you will need to use a real web server rather than TestHTTPD, but the basic strategy is sound run Apache Bench from a number of clients against one server which runs SNIProxy and proxies to one or more webservers (I would recommend nginx) on the local network. You could tweak this to meet your use case by using DNS resolution and whatever other features you are using in production. I would start by running sniproxy inside time, to gather coarse grain metrics. 

I've just pushed a 'profile-nonblocking-connect' branch, which tracks events on each individual connection and outputs the log of any connections taking more than 5ms  to complete (you can tune this in connection.c:slow_connection()). I've been maintaining this branch locally to profile the response to various conditions.

I agree, that at some point in order to scale SNIProxy it will be necessary to introduce a threading model, or use a multiprocessing model with multiple worker processes which handle the actual connection datapath. At the moment, I remain unconvinced that this radical change will benefit the majority of users. I would be happy to follow up via email to discuss your specific requirements in detail.

**Comment by balyanrobin** [comment]
Hi,

I must agree to the fact that the performance delivered by SNIProxy is par/better as compared to some of very well known proxy services out there and we all users must be thankful to you and the community for writing such a good quality software. 

I did some load testing and continuing to do that. here are the setup details which i am using on AWS. It may not be the ideal setup but more or less this is what i need in production and i want to eliminate the HAProxy layer to save hardware, maintenance cost, and delay induced even if it is negligible as every millisecond counts in web world. In most of my tests i hit the network bandwidth first on AWS, but in real scenario the box will have capability to handle 10 to 20 Gbps and in that case one CPU won’t be enough as currently it is hitting almost 35 to 40 percent on single core. I may not need the Multi processes in normal scenarios but i doubt the production deployment can be scaled with single process.

Test Setup:
40 to 60 Bees with machine guns(using apache bench internally) with concurrency of up to 1k concurrent requests
Hitting HAProxy load balancing SNIProxy 4 to 8 instances.
4 to 8 instances sitting on 2 multicore high end boxes.
Nginx serving static files of 10KB to 100KB sitting on multicore high end box.

I will go through the performance test approach suggested below and will update you more. I plan to run some more very specific test to see the max throughput i get from single SNIProxy server by eliminating the HAProxy in above configuration. I will share the results with you soon.

As a request, Is it possible for you to give me hints on how to make it multi process as i want to test it. I want to listen on one port and need to allow multiple SNIProxy processes sharing the load.

Regards,
Robin Balyan
| * balyanrobin@gmail.com <mailto:balyanrobin@gmail.com> | +1(617)816-2426

On 25-Feb-2015, at 12:24 pm, Dustin Lundquist <notifications@github.com> wrote:

@balyanrobin <https://github.com/balyanrobin> have you profiled the existing deployment? Do you know what percentage of CPU time is spent servicing system calls verses in user space? Have you seen anything that may point to what your current bottle neck is? I've done some limiting profiling using the test suite (e.g. cd tests; ./functional_test valgrind --tool=callgrind) and user space time is pretty well distributed, with the majority of it spend formatting access log messages.

You might take a look at tests/bench_sniproxy as a starting place for a test on your existing systems. For any meaningful measurements you will need to use a real web server rather than TestHTTPD, but the basic strategy is sound run Apache Bench from a number of clients against one server which runs SNIProxy and proxies to one or more webservers (I would recommend nginx) on the local network. You could tweak this to meet your use case by using DNS resolution and whatever other features you are using in production. I would start by running sniproxy inside time, to gather coarse grain metrics.

I've just pushed a 'profile-nonblocking-connect' branch, which tracks events on each individual connection and outputs the log of any connections taking more than 5ms to complete (you can tune this in connection.c:slow_connection()). I've been maintaining this branch locally to profile the response to various conditions.

I agree, that at some point in order to scale SNIProxy it will be necessary to introduce a threading model, or use a multiprocessing model with multiple worker processes which handle the actual connection datapath. At the moment, I remain unconvinced that this radical change will benefit the majority of users. I would be happy to follow up via email to discuss your specific requirements in detail.

**Comment by balyanrobin** [comment]
Hi,

I must agree to the fact that the performance delivered by SNIProxy is par/better as compared to some of very well known proxy services out there and we all users must be thankful to you and the community for writing such a good quality software. 

I did some load testing and continuing to do that. here are the setup details which i am using on AWS. It may not be the ideal setup but more or less this is what i need in production and i want to eliminate the HAProxy layer to save hardware, maintenance cost, and delay induced even if it is negligible as every millisecond counts in web world. In most of my tests i hit the network bandwidth first on AWS, but in real scenario the box will have capability to handle 10 to 20 Gbps and in that case one CPU won’t be enough as currently it is hitting almost 35 to 40 percent on single core. I may not need the Multi processes in normal scenarios but i doubt the production deployment can be scaled with single process.

Test Setup:
40 to 60 Bees with machine guns(using apache bench internally) with concurrency of up to 1k concurrent requests
Hitting HAProxy load balancing SNIProxy 4 to 8 instances.
4 to 8 instances sitting on 2 multicore high end boxes.
Nginx serving static files of 10KB to 100KB sitting on multicore high end box.

I will go through the performance test approach suggested below and will update you more. I plan to run some more very specific test to see the max throughput i get from single SNIProxy server by eliminating the HAProxy in above configuration. I will share the results with you soon.

As a request, Is it possible for you to give me hints on how to make it multi process as i want to test it. I want to listen on one port and need to allow multiple SNIProxy processes sharing the load.

Regards,
Robin

**Comment by balyanrobin** [comment]
Attaching the results sheet

![sniproxy_performance_test](https://cloud.githubusercontent.com/assets/6022699/6385357/b1dcc63a-bd36-11e4-8e25-e91dc880cbe5.png)

**Comment by balyanrobin** [comment]
Please find the result sheet attached, not sure if you will receive this email, so uploaded on community page as well.




Regards,
Robin Balyan
| * balyanrobin@gmail.com <mailto:balyanrobin@gmail.com> | +1(617)816-2426

On 25-Feb-2015, at 1:20 pm, Robin Balyan <balyanrobin@gmail.com> wrote:

Hi,

I must agree to the fact that the performance delivered by SNIProxy is par/better as compared to some of very well known proxy services out there and we all users must be thankful to you and the community for writing such a good quality software. 

I did some load testing and continuing to do that. here are the setup details which i am using on AWS. It may not be the ideal setup but more or less this is what i need in production and i want to eliminate the HAProxy layer to save hardware, maintenance cost, and delay induced even if it is negligible as every millisecond counts in web world. In most of my tests i hit the network bandwidth first on AWS, but in real scenario the box will have capability to handle 10 to 20 Gbps and in that case one CPU won’t be enough as currently it is hitting almost 35 to 40 percent on single core. I may not need the Multi processes in normal scenarios but i doubt the production deployment can be scaled with single process.

Test Setup:
40 to 60 Bees with machine guns(using apache bench internally) with concurrency of up to 1k concurrent requests
Hitting HAProxy load balancing SNIProxy 4 to 8 instances.
4 to 8 instances sitting on 2 multicore high end boxes.
Nginx serving static files of 10KB to 100KB sitting on multicore high end box.

I will go through the performance test approach suggested below and will update you more. I plan to run some more very specific test to see the max throughput i get from single SNIProxy server by eliminating the HAProxy in above configuration. I will share the results with you soon.

As a request, Is it possible for you to give me hints on how to make it multi process as i want to test it. I want to listen on one port and need to allow multiple SNIProxy processes sharing the load.

Regards,
Robin Balyan
| * balyanrobin@gmail.com <mailto:balyanrobin@gmail.com> | +1(617)816-2426

On 25-Feb-2015, at 12:24 pm, Dustin Lundquist <notifications@github.com <mailto:notifications@github.com>> wrote:

@balyanrobin <https://github.com/balyanrobin> have you profiled the existing deployment? Do you know what percentage of CPU time is spent servicing system calls verses in user space? Have you seen anything that may point to what your current bottle neck is? I've done some limiting profiling using the test suite (e.g. cd tests; ./functional_test valgrind --tool=callgrind) and user space time is pretty well distributed, with the majority of it spend formatting access log messages.

You might take a look at tests/bench_sniproxy as a starting place for a test on your existing systems. For any meaningful measurements you will need to use a real web server rather than TestHTTPD, but the basic strategy is sound run Apache Bench from a number of clients against one server which runs SNIProxy and proxies to one or more webservers (I would recommend nginx) on the local network. You could tweak this to meet your use case by using DNS resolution and whatever other features you are using in production. I would start by running sniproxy inside time, to gather coarse grain metrics.

I've just pushed a 'profile-nonblocking-connect' branch, which tracks events on each individual connection and outputs the log of any connections taking more than 5ms to complete (you can tune this in connection.c:slow_connection()). I've been maintaining this branch locally to profile the response to various conditions.

I agree, that at some point in order to scale SNIProxy it will be necessary to introduce a threading model, or use a multiprocessing model with multiple worker processes which handle the actual connection datapath. At the moment, I remain unconvinced that this radical change will benefit the majority of users. I would be happy to follow up via email to discuss your specific requirements in detail.

**Comment by balyanrobin** [comment]
Hi,

I made it working by adding fork code and controlling it during signaling. It is not very decent, but with my limited knowledge of the language, that is all i could do. It works fine on 4 core machine and the performance is roughly 4 times. Would you be interested in looking at the changes i have done.

thanks a lot
Robin
