### ISSUE TITLE
Cut a new release containing the resolver functionality

### ISSUE THREAD

**Issue by robinbowes** [dlundquist/sniproxy#158]
I'd really like to use the DNS resolving capability of sniproxy and it appears that the configuration options to specify a local caching resolver have not yet been released.

Are you in a position to cut a new release any time soon?

R.

**Comment by dlundquist** [comment]
@robinbowes libudns includes built in support for specifying the DNS resolver via NAMESERVSER environmental variable, the resolver work was primarily intended to enable support for resolving AAAA records without breaking existing deployments which depend on the previous IPv4 only DNS resolution behavior. I should be able to work on a new release in the next two weeks.

**Comment by robinbowes** [comment]
That would be great - I'll bundle a build from git to keep me going for now (using the Fedora packaging).

I'm in the process of becoming co-maintainer of the sniproxy package in Fedora and specifically for EPEL7 so you might be hearing from me quite a bit more :)

R.

**Comment by dlundquist** [comment]
The 0.4.0 release was cut this morning.
