### ISSUE TITLE
dpkg-buildpackage Raspberry Pi

### ISSUE THREAD

**Issue by lasportsman13** [dlundquist/sniproxy#163]
Hi there,

Let me begin by saying that I'm a beginner with Raspberry Pi, Linux, and computer programming in general, so please be patient with me and forgive my lack of knowledge on the subject.

I'm an American university student currently studying abroad in Buenos Aires, Argentina. I'm still paying for all my services back in the US (Netflix, Amazon Prime, Comcast, HBO, etc.). Before I left, I set up a VPN using a Raspberry Pi Model B that I left at home in the US. Through it, I've been able to access my services. However, I've come to the understanding that this is not the best way of doing this as all the network traffic has to go through my Pi at home, which inevitably slows down the connection and causes the videos to lag or not load at all sometimes. From what I read online, it is better to set up a DNS server in the US instead of a VPN (something like an unblock us clone). 

So, that's what I went about trying to do (I am able to SSH into the Pi from here). I searched for how to set it up and came across this tutorial online: http://raspberrypihelp.net/tutorials/45-raspberry-pi-tunlr-clone that appears to be exactly what I need. I get about 2/3rd of the way through the process when I can't advance further, as the Pi keeps getting hung up on sniproxy. I do sudo git clone http://github.com/dlundquist/sniproxy.git, then I typed sudo apt-get install dpkg-dev cdbs debhelper dh-autoreconf libev-dev libpcre3-dev, and finally a cd into the sniproxy folder and try to do sudo dpkg-buildpackage. I am then stuck with this error log:

dpkg-buildpackage: source package sniproxy
dpkg-buildpackage: source version 0.4.0
dpkg-buildpackage: source changed by Dustin Lundquist <dustin@null-ptr.net>
dpkg-buildpackage: host architecture armhf
 dpkg-source --before-build sniproxy
 debian/rules clean
test -x debian/rules
dh_testroot
rm -f debian/stamp-makefile-build debian/stamp-makefile-install
/usr/bin/make  -C .  -k distclean
make[1]: Entering directory `/home/pi/sniproxy'
make[1]: *** No rule to make target `distclean'.
make[1]: Leaving directory `/home/pi/sniproxy'
make: [makefile-clean] Error 2 (ignored)
rm -f debian/stamp-autotools
rmdir --ignore-fail-on-non-empty .
rmdir: failed to remove `.': Invalid argument
make: [makefile-clean] Error 1 (ignored)
for i in   ./config.rpath ; do \
		if test -e $i.cdbs-orig ; then \
			mv $i.cdbs-orig $i ; \
		fi ; \
	done
dh_autoreconf_clean 
dh_clean 
rm -f debian/stamp-autotools-files
 dpkg-source -b sniproxy
dpkg-source: info: using source format `3.0 (native)'
dpkg-source: info: building sniproxy in sniproxy_0.4.0.tar.gz
dpkg-source: info: building sniproxy in sniproxy_0.4.0.dsc
 debian/rules build
test -x debian/rules
mkdir -p "."
/usr/share/cdbs/1/rules/buildcore.mk:109: WARNING:  DEB_DH_STRIP_ARGS is a deprecated variable
if test -e /usr/share/gnulib/build-aux/config.rpath ; then \
		for i in ./config.rpath ; do \
			if ! test -e $i.cdbs-orig ; then \
				mv $i $i.cdbs-orig ; \
				cp --remove-destination /usr/share/gnulib/build-aux/config.rpath $i ; \
			fi ; \
		done ; \
	fi
dh_autoreconf 
configure.ac:19: error: possibly undefined macro: AC_LIB_HAVE_LINKFLAGS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:21: error: possibly undefined macro: AC_SUBST
configure.ac:23: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:46: error: possibly undefined macro: AS_IF
autoreconf: /usr/bin/autoconf failed with exit status: 1
dh_autoreconf: autoreconf -f -i returned exit code 1
make: *** [debian/autoreconf.after] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

I decided to delete the folder, remove all the packages I had installed, did sudo apt-get update and sudo apt-get upgrade, and tried again, still to no avail. I then looked online and came across this thread: https://github.com/dlundquist/sniproxy/issues/76. I tried the solution from there, which was to type in touch config.rpath while I'm in the sniproxy folder but before I tried to build the package - still no luck.

I am unable to continue through the tutorial because I can't get sniproxy to build. Can anyone help me with this? (And a side note, if anyone could explain to me the difference between the VPN I had set up earlier and this DNS server - or just how this DNS server will work to unblock these services from outside the US - I would really appreciate it!)

Thanks!

**Comment by dlundquist** [comment]
It sounds like your missing some autoconf dependency. I would suggest install the package lists the README: `sudo apt-get install autotools-dev cdbs debhelper dh-autoreconf dpkg-dev gettext libev-dev libpcre3-dev libudns-dev pkg-config`. If you still have problems, please try the generic `./autogen.sh && ./configure && make check`.

**Comment by dlundquist** [comment]
I just verified I could build it on Raspbian. I had to build udns from its source package in order to satisfy the dependencies. Packages are up on http://gateway01.nssix.com/packages/ (the `-armel` files).

**Comment by diginfo** [comment]
Hi;

I am just attempting this on latest raspian, the nssix.com link is dead, any idea where else I can get the armel source files ?
