### ISSUE TITLE
reopen logger causing buffering of logs and disowner _IOLBF

### ISSUE THREAD

**Issue by balyanrobin** [dlundquist/sniproxy#164]
Reopen logger is causing the default logger behavior to change and after adding below mentioned line in reopen_loggers() issue gets fixed

setvbuf(sink->fd, NULL, _IOLBF, 0);

**Comment by balyanrobin** [comment]
setvbuf(sink->fd, NULL, _IOLBF, 0); fixes the issue

**Comment by dlundquist** [comment]
Fixed in  #165, thank you.
