### ISSUE TITLE
Refusing to proxy to socket address literal 

### ISSUE THREAD

**Issue by nielspeen** [dlundquist/sniproxy#166]
Is it possible to allow proxying to plain IP addresses (non-SSL only)? Unfortunately a lot of Chinese websites address their images and other resources through IP's instead of hostnames. These now break.

**Comment by dlundquist** [comment]
@nielspeen This behavior was disabled in ece963f because it could be used to access internal local services which were not intended to be published. It would be relatively easy to add a configuration option to re-enable this feature or revert that commit for local deployment.

**Comment by nielspeen** [comment]
Thanks. I'll revert the patch. 

Please consider making this optional. While I understand the potential security concerns, it breaks otherwise valid HTTP requests.

**Comment by dlundquist** [comment]
@nielspeen One note if you revert the patch, this will present a significant DoS potential if a client makes a HTTP request to a `Host: 127.0.0.1` header or similar causing sniproxy to recursively proxy to itself until it runs out of file descriptors, then return 503 and unroll all of those connections.
