### ISSUE TITLE
sniproxy_error - bind unix:/var/run/proxy.sock failed: Address already in use

### ISSUE THREAD

**Issue by erezrb** [dlundquist/sniproxy#167]
Hi,

i try to use sniproxy on debian 7 - 64 bit.
i'm using network has vmbr0 for public network and vmbr2 for nat.
i like to assess a web page on local openvz container with ip 192.168.0.1 

i'm geting and error:

sniproxy_error.log:
   bind unix:/var/run/proxy.sock failed: Address already in use
   Failed to initialize listener unix:/var/run/proxy.sock

thank you,
erez

**Comment by dlundquist** [comment]
@erezrb This error indicates that a path /var/run/proxy.sock. Either another copy of sniproxy is running, or a file exists at that path.

I suggest you take a look at that path, if it is a file move it out of the way and if it is a socket go ahead an remove it.

**Comment by erezrb** [comment]
Hi,

thank you,

how can i stop sniproxy from running to apply the new configuration ?
