### ISSUE TITLE
kernel oom error

### ISSUE THREAD

**Issue by bennergnz** [dlundquist/sniproxy#169]
I have successfully installed sniproxy on a Centos 6.6 VM. However when I remotely access using openssl from a remote computer it crashes. Checking /var/log/messages gives me the result below. No errors were reported in the sniproxy error or access logs.

Any ideas?

Jun 21 10:18:28 london kernel: named invoked oom-killer: gfp_mask=0x201da, order=0, oom_adj=0, oom_score_adj=0
Jun 21 10:18:28 london kernel: named cpuset=/ mems_allowed=0
Jun 21 10:18:28 london kernel: Pid: 891, comm: named Not tainted 2.6.32-504.12.2.el6.x86_64 #1
Jun 21 10:18:28 london kernel: Call Trace:
Jun 21 10:18:28 london kernel: [<ffffffff810d40c1>] ? cpuset_print_task_mems_allowed+0x91/0xb0
Jun 21 10:18:28 london kernel: [<ffffffff81127300>] ? dump_header+0x90/0x1b0
Jun 21 10:18:28 london kernel: [<ffffffff8122eb5c>] ? security_real_capable_noaudit+0x3c/0x70
Jun 21 10:18:28 london kernel: [<ffffffff81127782>] ? oom_kill_process+0x82/0x2a0
Jun 21 10:18:28 london kernel: [<ffffffff811276c1>] ? select_bad_process+0xe1/0x120
Jun 21 10:18:28 london kernel: [<ffffffff81127bc0>] ? out_of_memory+0x220/0x3c0
Jun 21 10:18:28 london kernel: [<ffffffff811344df>] ? __alloc_pages_nodemask+0x89f/0x8d0
Jun 21 10:18:28 london kernel: [<ffffffff8116c69a>] ? alloc_pages_current+0xaa/0x110
Jun 21 10:18:28 london kernel: [<ffffffff811246f7>] ? __page_cache_alloc+0x87/0x90
Jun 21 10:18:28 london kernel: [<ffffffff811240de>] ? find_get_page+0x1e/0xa0
Jun 21 10:18:28 london kernel: [<ffffffff81125697>] ? filemap_fault+0x1a7/0x500
Jun 21 10:18:28 london kernel: [<ffffffff8114eae4>] ? __do_fault+0x54/0x530
Jun 21 10:18:28 london kernel: [<ffffffff8114f0b7>] ? handle_pte_fault+0xf7/0xb00
Jun 21 10:18:28 london kernel: [<ffffffff8152aede>] ? mutex_lock+0x1e/0x50
Jun 21 10:18:28 london kernel: [<ffffffff81199517>] ? pipe_read+0x2a7/0x4e0
Jun 21 10:18:28 london kernel: [<ffffffff8114fcea>] ? handle_mm_fault+0x22a/0x300
Jun 21 10:18:28 london kernel: [<ffffffff8104d0d8>] ? __do_page_fault+0x138/0x480
Jun 21 10:18:28 london kernel: [<ffffffff814c1194>] ? udp_poll+0x24/0xb0
Jun 21 10:18:28 london kernel: [<ffffffff8122d576>] ? security_file_permission+0x16/0x20
Jun 21 10:18:28 london kernel: [<ffffffff8153003e>] ? do_page_fault+0x3e/0xa0
Jun 21 10:18:28 london kernel: [<ffffffff8152d3f5>] ? page_fault+0x25/0x30
Jun 21 10:18:28 london kernel: Mem-Info:
Jun 21 10:18:28 london kernel: Node 0 DMA per-cpu:
Jun 21 10:18:28 london kernel: CPU    0: hi:    0, btch:   1 usd:   0
Jun 21 10:18:28 london kernel: Node 0 DMA32 per-cpu:
Jun 21 10:18:28 london kernel: CPU    0: hi:  186, btch:  31 usd:  35
Jun 21 10:18:28 london kernel: active_anon:53803 inactive_anon:35 isolated_anon:0
Jun 21 10:18:28 london kernel: active_file:0 inactive_file:13 isolated_file:32
Jun 21 10:18:28 london kernel: unevictable:0 dirty:0 writeback:0 unstable:0
Jun 21 10:18:28 london kernel: free:1196 slab_reclaimable:12558 slab_unreclaimable:32327
Jun 21 10:18:28 london kernel: mapped:2 shmem:38 pagetables:529 bounce:0
Jun 21 10:18:28 london kernel: Node 0 DMA free:2044kB min:84kB low:104kB high:124kB active_anon:6072kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15368kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:1396kB slab_unreclaimable:3428kB kernel_stack:0kB pagetables:12kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
Jun 21 10:18:28 london kernel: lowmem_reserve[]: 0 489 489 489
Jun 21 10:18:28 london kernel: Node 0 DMA32 free:2740kB min:2784kB low:3480kB high:4176kB active_anon:209140kB inactive_anon:140kB active_file:0kB inactive_file:52kB unevictable:0kB isolated(anon):0kB isolated(file):128kB present:500952kB mlocked:0kB dirty:0kB writeback:0kB mapped:8kB shmem:152kB slab_reclaimable:48836kB slab_unreclaimable:125880kB kernel_stack:616kB pagetables:2104kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:77 all_unreclaimable? no
Jun 21 10:18:28 london kernel: lowmem_reserve[]: 0 0 0 0
Jun 21 10:18:28 london kernel: Node 0 DMA: 9_4kB 1_8kB 1_16kB 0_32kB 1_64kB 1_128kB 1_256kB 1_512kB 1_1024kB 0_2048kB 0_4096kB = 2044kB
Jun 21 10:18:28 london kernel: Node 0 DMA32: 127_4kB 33_8kB 7_16kB 0_32kB 1_64kB 0_128kB 1_256kB 1_512kB 1_1024kB 0_2048kB 0_4096kB = 2740kB
Jun 21 10:18:28 london kernel: 81 total pagecache pages
Jun 21 10:18:28 london kernel: 0 pages in swap cache
Jun 21 10:18:28 london kernel: Swap cache stats: add 0, delete 0, find 0/0
Jun 21 10:18:28 london kernel: Free swap  = 0kB
Jun 21 10:18:28 london kernel: Total swap = 0kB
Jun 21 10:18:28 london kernel: 131069 pages RAM
Jun 21 10:18:28 london kernel: 5514 pages reserved
Jun 21 10:18:28 london kernel: 171 pages shared
Jun 21 10:18:28 london kernel: 109869 pages non-shared
Jun 21 10:18:28 london kernel: [ pid ]   uid  tgid total_vm      rss cpu oom_adj oom_score_adj name
Jun 21 10:18:28 london kernel: [  302]     0   302     2679      121   0     -17         -1000 udevd
Jun 21 10:18:28 london kernel: [  547]     0   547     2678      120   0     -17         -1000 udevd
Jun 21 10:18:28 london kernel: [  807]     0   807     6899       59   0     -17         -1000 auditd
Jun 21 10:18:28 london kernel: [  837]     0   837    62271      136   0       0             0 rsyslogd
Jun 21 10:18:28 london kernel: [  888]    25   888    40144     2411   0       0             0 named
Jun 21 10:18:28 london kernel: [  940]     0   940     1020       29   0       0             0 acpid
Jun 21 10:18:28 london kernel: [  960]     0   960    16554      177   0     -17         -1000 sshd
Jun 21 10:18:28 london kernel: [ 1037]     0  1037    20214      226   0       0             0 master
Jun 21 10:18:28 london kernel: [ 1046]    89  1046    20234      219   0       0             0 pickup
Jun 21 10:18:28 london kernel: [ 1047]    89  1047    20276      219   0       0             0 qmgr
Jun 21 10:18:28 london kernel: [ 1049]     0  1049    29216      152   0       0             0 crond
Jun 21 10:18:28 london kernel: [ 1068]     0  1068     1016       21   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1070]     0  1070     1016       22   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1072]     0  1072     1016       22   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1074]     0  1074     1016       21   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1076]     0  1076     1016       22   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1078]     0  1078     1016       22   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1091]     0  1091    25624      256   0       0             0 sshd
Jun 21 10:18:28 london kernel: [ 1093]     0  1093    27076       91   0       0             0 bash
Jun 21 10:18:28 london kernel: [ 1151]     2  1151    53316    49460   0       0             0 sniproxy
Jun 21 10:18:28 london kernel: [ 1153]     0  1153     3283       31   0       0             0 sniproxy
Jun 21 10:18:28 london kernel: [ 1154]     0  1154    25236       25   0       0             0 tail
Jun 21 10:18:28 london kernel: Out of memory: Kill process 1151 (sniproxy) score 394 or sacrifice child
Jun 21 10:18:28 london kernel: Killed process 1153, UID 0, (sniproxy) total-vm:13132kB, anon-rss:124kB, file-rss:0kB
Jun 21 10:18:28 london kernel: named invoked oom-killer: gfp_mask=0x201da, order=0, oom_adj=0, oom_score_adj=0
Jun 21 10:18:28 london kernel: named cpuset=/ mems_allowed=0
Jun 21 10:18:28 london kernel: Pid: 891, comm: named Not tainted 2.6.32-504.12.2.el6.x86_64 #1
Jun 21 10:18:28 london kernel: Call Trace:
Jun 21 10:18:28 london kernel: [<ffffffff810d40c1>] ? cpuset_print_task_mems_allowed+0x91/0xb0
Jun 21 10:18:28 london kernel: [<ffffffff81127300>] ? dump_header+0x90/0x1b0
Jun 21 10:18:28 london kernel: [<ffffffff8122eb5c>] ? security_real_capable_noaudit+0x3c/0x70
Jun 21 10:18:28 london kernel: [<ffffffff81127782>] ? oom_kill_process+0x82/0x2a0
Jun 21 10:18:28 london kernel: [<ffffffff811276c1>] ? select_bad_process+0xe1/0x120
Jun 21 10:18:28 london kernel: [<ffffffff81127bc0>] ? out_of_memory+0x220/0x3c0
Jun 21 10:18:28 london kernel: [<ffffffff811344df>] ? __alloc_pages_nodemask+0x89f/0x8d0
Jun 21 10:18:28 london kernel: [<ffffffff8116c69a>] ? alloc_pages_current+0xaa/0x110
Jun 21 10:18:28 london kernel: [<ffffffff811246f7>] ? __page_cache_alloc+0x87/0x90
Jun 21 10:18:28 london kernel: [<ffffffff811240de>] ? find_get_page+0x1e/0xa0
Jun 21 10:18:28 london kernel: [<ffffffff81125697>] ? filemap_fault+0x1a7/0x500
Jun 21 10:18:28 london kernel: [<ffffffff8114eae4>] ? __do_fault+0x54/0x530
Jun 21 10:18:28 london kernel: [<ffffffff8114f0b7>] ? handle_pte_fault+0xf7/0xb00
Jun 21 10:18:28 london kernel: [<ffffffff8152aede>] ? mutex_lock+0x1e/0x50
Jun 21 10:18:28 london kernel: [<ffffffff81199517>] ? pipe_read+0x2a7/0x4e0
Jun 21 10:18:28 london kernel: [<ffffffff8114fcea>] ? handle_mm_fault+0x22a/0x300
Jun 21 10:18:28 london kernel: [<ffffffff8104d0d8>] ? __do_page_fault+0x138/0x480
Jun 21 10:18:28 london kernel: [<ffffffff814c1194>] ? udp_poll+0x24/0xb0
Jun 21 10:18:28 london kernel: [<ffffffff8122d576>] ? security_file_permission+0x16/0x20
Jun 21 10:18:28 london kernel: [<ffffffff8153003e>] ? do_page_fault+0x3e/0xa0
Jun 21 10:18:28 london kernel: [<ffffffff8152d3f5>] ? page_fault+0x25/0x30
Jun 21 10:18:28 london kernel: Mem-Info:
Jun 21 10:18:28 london kernel: Node 0 DMA per-cpu:
Jun 21 10:18:28 london kernel: CPU    0: hi:    0, btch:   1 usd:   0
Jun 21 10:18:28 london kernel: Node 0 DMA32 per-cpu:
Jun 21 10:18:28 london kernel: CPU    0: hi:  186, btch:  31 usd: 101
Jun 21 10:18:28 london kernel: active_anon:53789 inactive_anon:35 isolated_anon:0
Jun 21 10:18:28 london kernel: active_file:7 inactive_file:0 isolated_file:32
Jun 21 10:18:28 london kernel: unevictable:0 dirty:0 writeback:0 unstable:0
Jun 21 10:18:28 london kernel: free:1165 slab_reclaimable:12558 slab_unreclaimable:32327
Jun 21 10:18:28 london kernel: mapped:2 shmem:38 pagetables:519 bounce:0
Jun 21 10:18:28 london kernel: Node 0 DMA free:2044kB min:84kB low:104kB high:124kB active_anon:6072kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15368kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:1396kB slab_unreclaimable:3428kB kernel_stack:0kB pagetables:12kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
Jun 21 10:18:28 london kernel: lowmem_reserve[]: 0 489 489 489
Jun 21 10:18:28 london kernel: Node 0 DMA32 free:2616kB min:2784kB low:3480kB high:4176kB active_anon:209084kB inactive_anon:140kB active_file:28kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):128kB present:500952kB mlocked:0kB dirty:0kB writeback:0kB mapped:8kB shmem:152kB slab_reclaimable:48836kB slab_unreclaimable:125880kB kernel_stack:616kB pagetables:2064kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:90 all_unreclaimable? yes
Jun 21 10:18:28 london kernel: lowmem_reserve[]: 0 0 0 0
Jun 21 10:18:28 london kernel: Node 0 DMA: 9_4kB 1_8kB 1_16kB 0_32kB 1_64kB 1_128kB 1_256kB 1_512kB 1_1024kB 0_2048kB 0_4096kB = 2044kB
Jun 21 10:18:28 london kernel: Node 0 DMA32: 130_4kB 28_8kB 1_16kB 0_32kB 1_64kB 0_128kB 1_256kB 1_512kB 1_1024kB 0_2048kB 0_4096kB = 2616kB
Jun 21 10:18:28 london kernel: 81 total pagecache pages
Jun 21 10:18:28 london kernel: 0 pages in swap cache
Jun 21 10:18:28 london kernel: Swap cache stats: add 0, delete 0, find 0/0
Jun 21 10:18:28 london kernel: Free swap  = 0kB
Jun 21 10:18:28 london kernel: Total swap = 0kB
Jun 21 10:18:28 london kernel: 131069 pages RAM
Jun 21 10:18:28 london kernel: 5514 pages reserved
Jun 21 10:18:28 london kernel: 160 pages shared
Jun 21 10:18:28 london kernel: 109845 pages non-shared
Jun 21 10:18:28 london kernel: [ pid ]   uid  tgid total_vm      rss cpu oom_adj oom_score_adj name
Jun 21 10:18:28 london kernel: [  302]     0   302     2679      121   0     -17         -1000 udevd
Jun 21 10:18:28 london kernel: [  547]     0   547     2678      120   0     -17         -1000 udevd
Jun 21 10:18:28 london kernel: [  807]     0   807     6899       59   0     -17         -1000 auditd
Jun 21 10:18:28 london kernel: [  837]     0   837    62271      136   0       0             0 rsyslogd
Jun 21 10:18:28 london kernel: [  888]    25   888    40144     2411   0       0             0 named
Jun 21 10:18:28 london kernel: [  940]     0   940     1020       29   0       0             0 acpid
Jun 21 10:18:28 london kernel: [  960]     0   960    16554      177   0     -17         -1000 sshd
Jun 21 10:18:28 london kernel: [ 1037]     0  1037    20214      226   0       0             0 master
Jun 21 10:18:28 london kernel: [ 1046]    89  1046    20234      219   0       0             0 pickup
Jun 21 10:18:28 london kernel: [ 1047]    89  1047    20276      219   0       0             0 qmgr
Jun 21 10:18:28 london kernel: [ 1049]     0  1049    29216      152   0       0             0 crond
Jun 21 10:18:28 london kernel: [ 1068]     0  1068     1016       21   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1070]     0  1070     1016       22   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1072]     0  1072     1016       22   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1074]     0  1074     1016       21   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1076]     0  1076     1016       22   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1078]     0  1078     1016       22   0       0             0 mingetty
Jun 21 10:18:28 london kernel: [ 1091]     0  1091    25624      256   0       0             0 sshd
Jun 21 10:18:28 london kernel: [ 1093]     0  1093    27076       91   0       0             0 bash
Jun 21 10:18:28 london kernel: [ 1151]     2  1151    53316    49460   0       0             0 sniproxy
Jun 21 10:18:28 london kernel: [ 1154]     0  1154    25236       25   0       0             0 tail
Jun 21 10:18:28 london kernel: Out of memory: Kill process 1151 (sniproxy) score 394 or sacrifice child
Jun 21 10:18:28 london kernel: Killed process 1151, UID 2, (sniproxy) total-vm:213264kB, anon-rss:197836kB, file-rss:4kB
Jun 21 10:18:28 london kernel: __ratelimit: 14550 callbacks suppressed
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow
Jun 21 10:18:28 london kernel: TCP: time wait bucket table overflow

**Comment by dlundquist** [comment]
That is strange, it looks like sniproxy was using about 200MB of memory on a 512MB VM when the system ran out of memory. My running instances uses a tenth of that on a x86_64 platform. What version are you running? Is there anything unusual in your configuration?

**Comment by bennergnz** [comment]
I was running a fresh install (latest) on a clean install of Centos 6.6.

**Comment by Copytalky** [comment]
Can we see your configuration bennergnz?
