### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by daniel-lucio** [dlundquist/sniproxy#170]
Hi

Is there a simple rule to do server sizing?

**Comment by dlundquist** [comment]
Memory usage is very modest. People have successfully run sniproxy on embedded WRT devices. The largest memory use is the two 4k buffers per connection.

Profiling the memory usage during the functional test:
```
HEAP SUMMARY:
    in use at exit: 1,688 bytes in 5 blocks
  total heap usage: 746 allocs, 741 frees, 901,645 bytes allocated
```
