### ISSUE TITLE
Support for PROXY protocol

### ISSUE THREAD

**Issue by nielspeen** [dlundquist/sniproxy#171]
Is it possible to add support for the PROXY protocol?

http://www.haproxy.org/download/1.6/doc/proxy-protocol.txt

If I understand the spec correctly it's not necessary to terminate SSL or change anything else to the connection, other than inject a small binary header.

**Comment by dlundquist** [comment]
@nielspeen If its just prepending a header onto the TCP stream to the backend server it wouldn't be too hard to add. This could take place immediately before `initate_server_connect()`, after the hostname has been resolved.

There are some details to work out with the buffer module, it doesn't presently support prepending and there is the possibility that the initial client request could fill the buffer and there wouldn't be room for the PROXY protocol header. One approach would be to initialize the buffer with a blank PROXY header, and discard or fill out the header once the backend server decision has been made.

**Comment by romaincointepas** [comment]
Would love to see this as well!
