### ISSUE TITLE
sniproxy appears to ignore hosts file

### ISSUE THREAD

**Issue by adammw** [dlundquist/sniproxy#174]
I'm trying to use sniproxy inside a docker container and link it to other containers using the --link directive, which populates names into the /etc/hosts file, however in SNIproxy I just get "backend not available". I suspect that sniproxy is using UDNS instead of checking the hosts file.

**Comment by dlundquist** [comment]
Sniproxy does not check the hosts file. If you have static host mappings, I would recommend include them in the sniproxy configuration so there will not be any additional lookup latency.
