### ISSUE TITLE
Failed to compile on Centos 6

### ISSUE THREAD

**Issue by syonmsn** [dlundquist/sniproxy#177]
[root@k sniproxy-master]#  ./autogen.sh && ./configure && make dist
./setver.sh: line 35: debchange: command not found
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/root/sniproxy-master':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details.

[root@k sniproxy-master]# tail config.log

#define PACKAGE_NAME "sniproxy"
#define PACKAGE_TARNAME "sniproxy"
#define PACKAGE_VERSION "0.4.0"
#define PACKAGE_STRING "sniproxy 0.4.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE "sniproxy"
#define VERSION "0.4.0"

configure: exit 1

**Comment by Zacktamondo** [comment]
if anyone face the same issue `yum install gcc`
