### ISSUE TITLE
can not deal with softether sstp server

### ISSUE THREAD

**Issue by Destitution** [dlundquist/sniproxy#183]
sniproxy is a gorgeous tool that can reuse 443 port, which works fine with nginx and ocserv.
but seemed that it can not deal with softether.
authentication succeeds when establishing an sstp connection with server, which proves sniproxy workes well, and(but) the sstp connection brokes immediately.
here is config and log.
anyone helps?

listener 0.0.0.0:443 {
   protocol tls
   table TableName
   fallback 127.0.0.1:444
}
table TableName {
   www.mydomain.com 127.0.0.1:446       //softether sstp
   mydomain.com 127.0.0.1:444       //ocserv
   anotherdomain.com 127.0.0.1:445      //nginx https
}

log:
2016-01-28 00:38:48 Request from xxx.xxx.xxx.xxx:51970 did not include a hostname
2016-01-28 00:38:48 No match found for (null)

**Comment by dlundquist** [comment]
According to the SSTP Wikipedia page [1] it uses SSL 3.0 which doesn't
include the TLS SNI extension. It should work if you use the listener
fallback directive.

[1] https://en.wikipedia.org/wiki/Secure_Socket_Tunneling_Protocol

**Comment by bitching** [comment]
acctually it's not possible to establish an sstp connection without tls, which softether supports indeed.
[1] https://social.technet.microsoft.com/Forums/windows/en-US/8db7cb80-5812-4582-bec2-293525bbd7a5/windows-7-sstp-over-tls-11tls-12
[2] https://www.softether.org/3-spec

**Comment by dlundquist** [comment]
@bitching in that wireshark screenshot it looks like the client sent a SSL client hello, for SNIproxy to work the client hello must be TLS and include the Server Name Indication extension. You could examine a client hello and verify it is using TLS and has the expected hostname in the SNI extension. Without an SNI extension, there isn't a way to make forwarding decision.

**Comment by comp500** [comment]
SSTP with SoftEther through SNIproxy seems to work great for me. I've tested it with both my Surface (8.1 RT) and my phone ([using this client](https://play.google.com/store/apps/details?id=it.colucciweb.sstpvpnclient&hl=en_GB)) and they send TLS 1.2 ClientHello packets with correct server_name extension.
