### ISSUE TITLE
debchange: not found

### ISSUE THREAD

**Issue by chovy** [dlundquist/sniproxy#188]
Getting this error on Ubuntu 15.10

```
./autogen.sh && dpkg-buildpackage
./setver.sh: 35: ./setver.sh: debchange: not found
autoreconf: automake terminated by signal: 2
```

**Comment by chovy** [comment]
`sudo apt-get install devscripts` fixed it

**Comment by simos** [comment]
_debchange_ is not essential and you can ignore the message. 

The issue with installing _devscripts_ is that it pulls in lots of packages:

  binutils build-essential cpp cpp-4.8 dctrl-tools devscripts diffstat
  distro-info-data dpkg-dev dput fakeroot g++ g++-4.8 gcc gcc-4.8 gettext
  hardening-includes intltool-debian libalgorithm-diff-perl
  libalgorithm-diff-xs-perl libalgorithm-merge-perl libapt-pkg-perl
  libarchive-zip-perl libasan0 libasprintf-dev libatomic1 libauthen-sasl-perl
  libautodie-perl libc-dev-bin libc6-dev libclone-perl libcloog-isl4
  libcommon-sense-perl libcroco3 libdigest-hmac-perl libdistro-info-perl
  libdpkg-perl libemail-valid-perl libencode-locale-perl liberror-perl
  libexporter-lite-perl libfakeroot libfile-basedir-perl
  libfile-fcntllock-perl libfile-listing-perl libfont-afm-perl libgcc-4.8-dev
  libgettextpo-dev libgettextpo0 libgmp10 libgomp1 libhtml-form-perl
  libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl
  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl
  libhttp-message-perl libhttp-negotiate-perl libio-html-perl libio-pty-perl
  libio-socket-inet6-perl libio-socket-ssl-perl libio-stringy-perl
  libipc-run-perl libipc-system-simple-perl libisl10 libitm1 libjson-perl
  libjson-xs-perl liblist-moreutils-perl liblwp-mediatypes-perl
  liblwp-protocol-https-perl libmailtools-perl libmpc3 libmpfr4
  libnet-dns-perl libnet-domain-tld-perl libnet-http-perl libnet-ip-perl
  libnet-smtp-ssl-perl libnet-ssleay-perl libparse-debcontrol-perl
  libperlio-gzip-perl libquadmath0 libsocket6-perl libstdc++-4.8-dev
  libsub-identify-perl libtext-levenshtein-perl libtie-ixhash-perl libtsan0
  libunistring0 liburi-perl libwww-perl libwww-robotrules-perl lintian
  linux-libc-dev make manpages-dev patchutils python3-chardet python3-debian
  python3-magic python3-pkg-resources python3-six t1utils unzip wdiff
