### ISSUE TITLE
Browser just waiting for site to load.

### ISSUE THREAD

**Issue by rick5505** [dlundquist/sniproxy#190]
Hi, I am trying to get this to work on my VPS. I have shutdown Apache while I test. 

In my http_access.log I get :
2016-02-15 11:32:24 87.x1.x2.x3:58188 -> 172.245.y2.y3:80 -> NONE [www.netflix.com] 114/114 bytes tx 0/1024 bytes rx 0.005 seconds

Should it state NONE like that?

In my /var/log/sniproxy/sniproxy.log I get :
2016-02-15 11:39:50 unable to resolve localhost, closing connection

This seems to be the main problem, maybe?

My NAS at home forwards the netflix.com to my VPS. When I lookup from my home client the host points to my VPS public, just like your example.

I know this is an old thread but I would really like to get this working. I realize Netflix is probably not going to work, but HBOGO, Amazon Prime, and ESPNGO may still work.

Thanks for any help.
Rick

**Comment by dlundquist** [comment]
This looks like a DNS resolution issue. SNIproxy is unable to resolve www.netflix.com so it closes the connection.
