### ISSUE TITLE
prevent unauthorized usage of proxy server

### ISSUE THREAD

**Issue by chovy** [dlundquist/sniproxy#192]
Is there a way I can maintain a whitelist of ips/hostnames that are allowed to use my sniproxy server?

I found within a few days its been discovered and people are using it now.

**Comment by jornane** [comment]
I use the firewall on my operating system or router to whitelist certain hosts. I don't think it's a task for sniproxy to do this.

**Comment by chovy** [comment]
I figured it out using ipset and iptables.
