### ISSUE TITLE
Squid in front of sniproxy

### ISSUE THREAD

**Issue by chezmojo** [dlundquist/sniproxy#196]
I had a stupid issue that I figured out.

**Comment by chovy** [comment]
what was it?

**Comment by chezmojo** [comment]
Connecting to the sniproxy via ipv6 and having it resolve ipv4 targets was breaking my squid proxy because it always resolves ipv6 addresses by default. But the problem turned out to be a problem with iptables6, not sniproxy. It caused squid to throw 'TCP_MISS_ABORTED' errors.
