### ISSUE TITLE
Connection: keep-alive

### ISSUE THREAD

**Issue by chovy** [dlundquist/sniproxy#198]
Sniproxy seems to fail when a request has the header `Connection: keep-alive`

**Comment by jornane** [comment]
Works for me. Do you have more details?

**Comment by chovy** [comment]
I was running some streams through a sniproxy and they kept dropping. As soon as I removed the `Connection: keep-alive` request header it worked fine.

**Comment by vavrecan** [comment]
It might have nothing to do with connection: keep-alive - Keep alive will keep tcp session open meanwhile when you go without keep alive more tcp sessions will get created. Well, i would sugest enabling sniproxy debug log and digging the issue out.

**Comment by dlundquist** [comment]
Sniproxy should be transparent regardless of the Connection header.  It doesn't participate in the HTTP or TLS protocol once the backend server connection is established. The backend server would be responsible to maintain keep-alives with the client through sniproxy. Testing with HTTP connections and debug enabled would be a good place to start.

**Comment by dlundquist** [comment]
Marking this as Won't Fix and closing, since sniproxy doesn't participate at the HTTP protocol level.
