### ISSUE TITLE
Not loading .conf file when compiling under Suse

### ISSUE THREAD

**Issue by daniel-lucio** [dlundquist/sniproxy#200]
Compiling source in Suse, i get an error saying that the .conf is unparsable.
Using another distro works. Do you have any comment? maybe an incompatible library from suse?

**Comment by dlundquist** [comment]
Could you try running sniproxy in the foreground under strace to see what it's doing? `strace sniproxy -f -c /path/to/sniproxy.conf`

**Comment by daniel-lucio** [comment]
i found reason :)  it needs udns lib :) thanks any way
