### ISSUE TITLE
Run in foreground *AND* drop privileges?

### ISSUE THREAD

**Issue by sjlongland** [dlundquist/sniproxy#203]
Hi,

Silly question, is there a way to get `sniproxy` to drop privileges after binding to sockets but still remain in the foreground?  The use case is for running `sniproxy` in a Docker container using `supervisord` which expects processes to stay in the foreground.

The docker container in question is here: https://hub.docker.com/r/vrtsystems/sniproxy/

I still want it to drop privileges though as it offers better security.  Perhaps a `--no-daemon` option could be added for this?

**Comment by dlundquist** [comment]
Not presently, it would be easy enough to add to `main()` in sniproxy.c. I would have to think about the implications of dropping privileges without

**Comment by dlundquist** [comment]
Actually, dropping permissions is already independent of running in the background: https://github.com/dlundquist/sniproxy/blob/master/src/sniproxy.c#L104-L122. If launched as root and a non-root user is specified in the configuration file, permissions will be dropped after opening listening sockets.

**Comment by sjlongland** [comment]
On 22/06/16 05:17, Dustin Lundquist wrote:
> Actually, dropping permissions is already independent of running in the
> background:
> https://github.com/dlundquist/sniproxy/blob/master/src/sniproxy.c#L104-L122.
> If launched as root and a non-root user is specified in the
> configuration file, permissions will be dropped after opening listening
> sockets.
Ahh okay, this wasn't apparent from the description of the flag, the "do
not drop privs" suggests it doesn't work that way.

By the looks of things, removal of that part of the help string is all
that's needed.

Many thanks for having a look. :-)
