### ISSUE TITLE
how to use reverse proxy with sniproxy

### ISSUE THREAD

**Issue by wangtubs** [dlundquist/sniproxy#207]
hi, I want to use my domain to reverse proxy some videos, because these videos are not available in some countries.
how should I configure the nginx to proxy video traffic through sniproxy? In this case, I should set up sniproxy in another vps?
thanks

**Comment by dlundquist** [comment]
Several people have written articles on using sniproxy to proxy certain video streaming sites. This is not my intended use, and due to the interests of copyright holders I'm not going provide support on using sniproxy for this purpose. I would be happy to look at defects within sniproxy.
