### ISSUE TITLE
lookup whois in the use of the 43 port in the sniproxy should be how to configure?

### ISSUE THREAD

**Issue by quyunet** [dlundquist/sniproxy#212]
lookup whois in the use of the 43 port in the sniproxy should be how to configure? the sniproxy can not support tcp protocol?

listen 43 {
proto tcp
table http_hosts
access_log {
filename /var/log/sniproxy/http_access.log
priority notice
}
}

**Comment by dlundquist** [comment]
I haven't looked at the whois protocol. Sniproxy presently supports HTTP
(1.1) and TLS, both of which provide a means for sending the requested
hostname within higher level protocol and then proxy the TCP session on a
backend found looking up that hostname in the table. You can add another
protocol, see protocol.h for the interface a protocol module needs to
fulfill.

**Comment by quyunet** [comment]
how to add an protocol? you can provide specific methods or example? thank you very much!

**Comment by quyunet** [comment]
http_access.log record:
2016-09-16 17:14:38 [::ffff:120.76.28.88]:39300 -> [::]:43 -> NONE [] 7/7 bytes tx 10/20 bytes rx 0.000 seconds

**Comment by quyunet** [comment]
@dlundquist Very good, updated to Sniproxy v0.5.0, the issue has been successfully solved, thank you very much!

**Comment by dlundquist** [comment]
@quyunet repots this issue resolved in 0.5.0 release.
