### ISSUE TITLE
[Help] Any way to redirect http->https?

### ISSUE THREAD

**Issue by InAnimaTe** [dlundquist/sniproxy#223]
I may actually be blind but I'm not seeing any way to do this.

Thanks

**Comment by dlundquist** [comment]
No there isn't a way to do this within SNIproxy itself, you'll need to use a web server such as Nginx. You can proxy only specific hosts by forwarding to UNIX sockets: http://gateway01.nssix.com/ .

-Dustin

**Comment by InAnimaTe** [comment]
Exactly what I expected. Just wanted to verify. Thanks for the quick response.
