### ISSUE TITLE
LEDE/OpenWRT

### ISSUE THREAD

**Issue by fabio70mi** [dlundquist/sniproxy#231]
Could be possible to have sniproxy as a LEDE/OpenWRT package,
maybe in their feeds ?

**Comment by dlundquist** [comment]
I've heard of folks running sniproxy on OpenWRT, so I don't see any reason why a maintainer couldn't contribute an sniproxy package to OpenWRT. The obvious question: would OpenWRT accept such a package?

**Comment by fabio70mi** [comment]
I think sniproxy could be useful for all the people wanting to access from internet several https services using port 443 inside home network having only one public IP address. I can configure LEDE/OpenWrt to proxy incoming SNI openvpn.myhome.net to openwrt openvpn service, to proxy www.myhome.net to internal web serve, to proxy wrt.myhome.net to proxy OpenWRT configuration webpage, and so on. I don't know what could be performance on budget OpenWRT routers, but should be very useful.

I'm not used to OpenWRT/LEDE opkg packaging and feeds structure, but I think if sniproxy has a own feed to add a sniproxy opkg package (like Libremesh has) could be easier to  add later to the LEDE/OpenWRT official feeds.

What do you think ?

**Comment by ttimasdf** [comment]
The same idea came across my mind and Google leads me here. But now I have a better solution. I could deploy a Raspberry Pi behind OpenWRT running sniproxy and make the router forward the 443 port for it. Even if we need a luci configuration page we could simply relay the traffic back to router. IMHO, SSL request handling itself is already a CPU intensive task and should not be done by router, not saying the domain routing, cgi or other scripting stuffs behind it. Let the router do what it's designed to do, and get things done easier as we don't need to "port" the codes any more.

**Comment by sigio** [comment]
https://gist.github.com/pkern/5497c63f16bfa261ba9131dbfd64e69e

These makefiles seem to work... so getting this into openwrt shouldn't be too much work for those with the correct permissions ;)

**Comment by rikka0w0** [comment]
> https://gist.github.com/pkern/5497c63f16bfa261ba9131dbfd64e69e
> 
> These makefiles seem to work... so getting this into openwrt shouldn't be too much work for those with the correct permissions ;)

It compiles on Openwrt 22.03.2, but when I install the generated package on my Openwrt router (DIR 853 A1, MT7621), it failed with "Segmentation Fault". The configuration that I used was tested on my PC.
