### ISSUE TITLE
sniproxy functionality in iptables

### ISSUE THREAD

**Issue by fabio70mi** [dlundquist/sniproxy#232]
Could be possible to have sniproxy functionality in iptables module ?

iptables could forward to an ip address based on incoming SNI

thank you.

**Comment by dlundquist** [comment]
The TLS Client Hello message isn't sent until the TCP handshake is complete, so for this to work the proxy server would need to proxy the TCP handshake. I suppose this could work with SYN cookies, or such, but there would need to be some way to pass on the TCP sequence number to the back end server. This doesn't seem like a good fit for a standard iptables match module, but maybe someone which more iptables knowledge can see how this could work.
