### ISSUE TITLE
resolver support  nameserver port not default 53

### ISSUE THREAD

**Issue by hnkeyang** [dlundquist/sniproxy#238]
my dns caching server not binding on port 53, can sniproxy support configuration nameserver port?

**Comment by dlundquist** [comment]
Not directly in SNIproxy, but you might try configuring it via libudns's resolver options facility: `export RES_OPTIONS="port=5353"`, alternatively you can compile libudns with an alternate `DNS_PORT` defined. Another option would be to use and iptables redirect.

**Comment by hnkeyang** [comment]
thanks !

**Comment by derd3000** [comment]
I know it's a litte bit stupid to comment in this old thread but I'm trying to get this working the hole day now...
I'm running a dnsmasq server on port 53 on which sniproxy should not resolv, so I'm running a second dnsmasq server with port 5300 in a docker container. everything works so far. sniproxy is also in a docker container. I don't get the iptables rule to redirect dns traffic from sniproxy to my imaginary dns resolver 123.123.123.123 to my local dns resolver 127.0.0.1:5300

In my optionion these iptables should work out, but they don't: :(

` iptables -t nat -A OUTPUT -p tcp -d 123.123.123.123 --dport 53 -j DNAT --to-destination 127.0.0.1:5300
 iptables -t nat -A OUTPUT -p udp -d 123.123.123.123 --dport 53 -j DNAT --to-destination 127.0.0.1:5300`
