### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by jandd** [dlundquist/sniproxy#240]
Hello,

I started to work on an official Debian package for sniproxy

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808132
https://anonscm.debian.org/cgit/collab-maint/sniproxy.git/log/?h=debian

I would like to package a recent version of sniproxy. My current packaging effort is based on a git commit id but I would like to package a released version, if possible.

Do you have any plans for a new release tag or should I just continue to base the packaging on a git commit id?

Best regards
Jan Dittberner

**Comment by dlundquist** [comment]
This is actually a good place to cut a stable release, current feature efforts: stats interface, LUA integration, table and configuration improvement are all likely to warrant a major version bump. Thank you!

**Comment by jandd** [comment]
Thanks for cuting a release. sniproxy is now officially in Debian unstable https://tracker.debian.org/news/844468
