### ISSUE TITLE
How to customize the default config location rather than `/etc/sniproxy.conf`

### ISSUE THREAD

**Issue by Neilpang** [dlundquist/sniproxy#246]
Is there a switch in the configure to customize the default config file ?
I know there is a `-c conf` parameter at runtime,   but what I'm asking is to customize the default conf location.

**Comment by dlundquist** [comment]
@Neilpang this is defined on the first line of main() in sniproxy.c. For a one-off build you can just change that line, a more sustainable option would be to make it a precompiler variable defined by autoconf like sniproxy_version (in the same file).

**Comment by Neilpang** [comment]
@dlundquist 
Thank you.
