### ISSUE TITLE
Reload_test failed on Raspbian

### ISSUE THREAD

**Issue by cbrandonmiller** [dlundquist/sniproxy#251]
I am trying to use sniproxy on a Raspberry Pi. I followed a tutorial, and it said to run ./autogen.sh && ./configure && make check. The check fails on reload_test. I have attached the test log.
`PASS: config_test
PASS: resolv_test
PASS: bad_dns_request_test
============================================================================
Testsuite summary for sniproxy 0.5.0
============================================================================
# TOTAL: 18
# PASS:  17
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
Makefile:822: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/pi/sniproxy/sniproxy-master/tests'
Makefile:928: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/pi/sniproxy/sniproxy-master/tests'
Makefile:1120: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/pi/sniproxy/sniproxy-master/tests'
Makefile:372: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
pi@raspberrypi:~/sniproxy/sniproxy-master $ nano tests/test-suite.log
  GNU nano 2.7.4              File: tests/test-suite.log

worker failed with exit code 7
worker failed with exit code 52
worker failed with exit code 7
worker failed with exit code 7
worker failed with exit code 52
worker failed with exit code 7
worker failed with exit code 52
worker failed with exit code 7
worker failed with exit code 52
worker failed with exit code 7
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 7
worker failed with exit code 7
FAIL reload_test (exit status: 1)
`

I found another tutorial that didn't run make check, so I compiled and installed Sniproxy. It says that the service is running, but I cannot get it to work. No matter what settings I set for the configuration file, it does not seem to be working. Could this be because of this test failing? If so, how can I fix this issue. If not, I can post a separate issue with that problem. The Raspberry Pi is running Raspbian Stretch, the newest version of Raspbian.

**Comment by dlundquist** [comment]
Could you provide the output of `tests/reload_test.log` and `tests/reload_test.trs`? Are there any other services running on TCP ports 8080, 8081, 8082, 8083 or 8084? Does the test fail reproducible after a restart? Sorry for the barrage of questions, but there isn't much information here to go on here.

**Comment by cbrandonmiller** [comment]
Sorry for the lack of information. Is the best way to give you the files just through the code tag, like I did on the initial post? I have to redownload the source to test it again, but it will only take a few minutes. The only thing the Pi is running is OpenVPN (with PiVPN) and Sniproxy. OpenVPN is running on the default port 1194. There shouldn't be anything running on 8080, 8081, 8082, 8083, or 8084, to the best of my knowledge. I am not super familiar with Linux, is there any easy way to see what ports are being used by services or anything like that?

**Comment by dlundquist** [comment]
@cbrandonmiller Using the code tag or triple single quotes would be great, they are simple text files. `ss -lptn` will give you a list of open TCP ports and which processes they are associated with.

**Comment by cbrandonmiller** [comment]
@dlundquist The only other port open is 22, for SSH. The test does fail consistently after rebooting and trying again. The requested files are attached below. 

reload_test.log
`Prototype mismatch: sub main::make_config ($$) vs ($$$) at ./reload_test line 76.
Subroutine make_config redefined at ./reload_test line 40.
2017-09-16 12:44:12 Parsed localhost 127.0.0.1:8083
2017-09-16 12:44:12 Parsed localhost 127.0.0.1:8083
2017-09-16 12:44:18 failed to reopen log file /tmp/Tt8SQ4TzTx: Permission denied
2017-09-16 12:44:18 reloading configuration from /tmp/9KqOVjkYKq
2017-09-16 12:44:18 init_config: unable to open configuration file: /tmp/9KqOVjkYKq
2017-09-16 12:44:18 failed to reload /tmp/9KqOVjkYKq
2017-09-16 12:44:19 recv(): Connection refused, closing connection
curl: (52) Empty reply from server
2017-09-16 12:44:19 recv(): Connection refused, closing connection
curl: (52) Empty reply from server
2017-09-16 12:44:20 recv(): Connection refused, closing connection
curl: (52) Empty reply from server
2017-09-16 12:44:20 recv(): Connection refused, closing connection
curl: (52) Empty reply from server
2017-09-16 12:44:20 recv(): Connection refused, closing connection
curl: (52) Empty reply from server
curl: (7) Failed to connect to localhost port 8082: Connection refused
2017-09-16 12:44:20 recv(): Connection refused, closing connection
curl: (7) Fcauirlle:d  (t5o2 )c oEnmnpetcyt  rteop llyo cfarlohmo sste rpvoerrt
 8082: Connection refused
2017-09-16 12:44:20 recv(): Connection refused, closing connection
curl: (52) Empty reply from server
curl: (7) Failed to connect to localhost port 8082: Connection refused
curl: (7) Failed to connect to localhost port 8082: Connection refused
2017-09-16 12:44:20 recv(): Connection refused, closing connection
curl: (7) Failed to connect to localhost porctu r8l0:8 2(:5 2C)o nEnmepcttyi orne prleyf ufsreodm
 server
2017-09-16 12:44:20 recv(): Connection refused, closing connection
curl: (52) Empty reply from server
curl: (7) Failed to connect to localhost port 8082: Connection refused
2017-09-16 12:44:20 recv(): Connection refused, closing connection
curl: (52) Empty reply from server
curl: c(u7r)l :F a(i7l)e dF atiol ecdo ntnoe ccto ntnoe clto ctaol hlooscta lphoorstt  8p0o8r2t:  8C0o8n2n:e cCtoinonne crteifouns erde
fused
curl: (7) Failed to connect to localhost port 8082: Connection refused
curl: (7) Failed to connect to localhost port 8082: Connection refused
Test failed.
worker failed with exit code 7
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 7
worker failed with exit code 7
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 7
worker failed with exit code 7
worker failed with exit code 7
worker failed with exit code 7
worker failed with exit code 7
worker failed with exit code 7
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 52
worker failed with exit code 7
FAIL reload_test (exit status: 1)
`

reload_test.trs
`:test-result: FAIL
:global-test-result: FAIL
:recheck: yes
:copy-in-global-log: yes
`

Please let me know if there is anything else I can do. I have experience with C++ and C# development, but I have never worked on anything this complex, especially in Linux.

**Comment by dlundquist** [comment]
Looks like something is up with your permissions in /tmp:
```
Subroutine make_config redefined at ./reload_test line 40.
2017-09-16 12:44:12 Parsed localhost 127.0.0.1:8083
2017-09-16 12:44:12 Parsed localhost 127.0.0.1:8083
2017-09-16 12:44:18 failed to reopen log file /tmp/Tt8SQ4TzTx: Permission denied
2017-09-16 12:44:18 reloading configuration from /tmp/9KqOVjkYKq
2017-09-16 12:44:18 init_config: unable to open configuration file: /tmp/9KqOVjkYKq
```

I would write it off to some customization in Rasperian and continue without `make check`.

**Comment by cbrandonmiller** [comment]
Ok. I have been able to compile and package it using the Debian instructions in the readme. However, I am still having an issue where Sniproxy does not seem to be receiving any requests. Should I create a separate issue for that, or do you want to continue it here? It is possible that it isn't actually something wrong with Sniproxy, but I'm not sure where to start.

**Comment by dlundquist** [comment]
@cbrandonmiller We can continue here.

I would start troubleshooting with the basics:

1. Is sniproxy running? Check the output of `ps faux` and ensure there is an sniproxy process.
2. Has it bound to a listening TCP port? Check the output of `sudo ss -lptn` -- sudo is necessary here to see the process associated with port if it running as another user.
3. Check the sniproxy logs. The log file location depends on the sniproxy configuration.

**Comment by cbrandonmiller** [comment]
@dlundquist  Thank you for your help. Below are the answers:

1. Yes, when I run ps faux, I see two sniproxy processes running, one as daemon and one as root.
2. sudo ss -lptn shows sniproxy running on 80 and 443.
3. I have the access log being created in the home directory for the user. It is created, but there are no entries in it.

For reference, here is the sniproxy.conf that I am using:
`user daemon
pidfile /var/tmp/sniproxy.pid

error_log {
    syslog daemon
    priority notice
}

access_log {
    # Same options as error_log
    filename /home/pi/sniproxy-access.log
}

listen 80 {
    protocol http
    table reroute
}

listen 443 {
    protocol tls
    table reroute
}

table reroute {
    whatismyip\.com *
    google\.com *
    starz\.com *
}`

I have Dnsmasq forwarding traffic from my local network for the same three domains to the sniproxy machine. The ISP where the machine running running Sniproxy is connected blocks ports 80 and 443 incoming, so I have my dnsmasq machine and the sniproxy machine connected with OpenVPN. They can see each other, and when I ping the domain, it shows me the IP of the sniproxy machine and says that it is getting a response. However, when I try to browse to one of those domains it just sits there trying and then says connection timed out.

**Comment by dlundquist** [comment]
It's best if we can troubleshoot one thing at a time, rather than the whole dnsmasq/openvpn config.

What happens when you run `curl -v -H 'Host: whatismyip.com' http://127.0.0.1` to send a test request to sniproxy? Anything in the log? Does the curl request complete?

You have your error log configured to log to syslog, anything `/var/log/daemon.log` (`grep sniproxy /var/log/daemon.log` to filter log contents)?

If there isn't anything in the error log (/var/log/daemon.log in your config), could you bump the log prioirty to debug from notice and try again?

**Comment by cbrandonmiller** [comment]
The curl appears to be successful. 

`* Rebuilt URL to: http://127.0.0.1/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: whatismyip.com
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Date: Sat, 16 Sep 2017 16:01:03 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Set-Cookie: __cfduid=de861be36253cf75e99b81350a2d3dc561505577663; expires=Sun, 16-Sep-18 16:01:03 GMT; path=/; domain=.whatismyip.com; HttpOnly
< Location: https://www.whatismyip.com/
< Server: cloudflare-nginx
< CF-RAY: 39f50acb856a558e-ORD
<
<html>
<head><title>301 Moved Permanently</title><script src="/cdn-cgi/apps/head/ktjkJYRfORkptzQ1DfimcRogHiA.js"></script></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
`

I hadn't figured out how to check the daemon log, I initially thought that is was what would show when you typed service sniproxy status. I tried it this way and also put it to a file to check that. No weird errors that I am seeing. The access log shows entries for each time I run the curl, but nothing otherwise. This is even with error log debug instead of priority. The only thing it shows is parsing the domains from the .conf file.

**Comment by dlundquist** [comment]
Well, based on your curl test it looks like sniproxy is successfully forwarding requests to whatismyip's cloud flare service. I think there is some other component that is causing your problem, sniproxy seems to be working. Since there is nothing in your access log, it sounds like your requests are not reach sniproxy. Perhaps your not using the raspberry pi as your DNS server or it doesn't have zones configured to direct traffic to it.

**Comment by cbrandonmiller** [comment]
My DNS server isn't on the sniproxy machine, it is in another pi that is on my local network. I definitely haven't set any zones or anything like that, so that could be the issue. None of the tutorials I have seen mentioned that for sniproxy, so I didn't know you needed to. I thought the listening on the port was all it needed.

I don't want to use the sniproxy as my dns server because it has a few hundred millisecond ping time. If I used it as my primary dns it would slow all my regular traffic down.

Can you point me in the right direction to resolve this issue? Is there a way to direct the traffic from the tunnel to sniproxy using iptables commands or something? Or if there is a way to direct dns overrides on my local dnsmasq server to another dns server on the sniproxy Pi? Thanks so much for taking the time to help me.

**Comment by cbrandonmiller** [comment]
@dlundquist Thanks for all your help, I got it working finally. I went back and tried the external IP on my sniproxy machine and it is working. The ISP told me that they would open the ports for me, I guess it just took a while. I also think I know why it wasn't working through the VPN. There are iptables rules to forward IP traffic from the vpn to the internet with POSTROUTING. Still trying to figure out how to get it to work.

I do have another question about sniproxy. If I add a domain to the config file and reboot the service, it won't work. The log says can't assign the port because it is already in use when I restart the service. It works once I reboot the Pi. Is there a way to get it to work without a full reboot?

**Comment by cbrandonmiller** [comment]
@dlundquist I have everything working through the VPN now. It was my own misunderstanding, not thinking enough about how Dnsmasq and Sniproxy work together. I now have everything going through the VPN.

I still seem to be having the issue I mentioned previously. If I add an additional site to my list, I have to completely reboot the machine before it will work. Also, I occasionally get an error about SSL cypher mismatch, any idea what would be causing that?
