### ISSUE TITLE
how can i fix this?   Package sniproxy is not installed.

### ISSUE THREAD

**Issue by zssnode** [dlundquist/sniproxy#252]
$ :~/sniproxy# dpkg -i ../sniproxy-dbg_0.5.0+git.11.gbe6169e_amd64.deb
Selecting previously unselected package sniproxy-dbg.
(Reading database ... 65600 files and directories currently installed.)
Preparing to unpack .../sniproxy-dbg_0.5.0+git.11.gbe6169e_amd64.deb ...
Unpacking sniproxy-dbg (0.5.0+git.11.gbe6169e) ...
dpkg: dependency problems prevent configuration of sniproxy-dbg:
 sniproxy-dbg depends on sniproxy (= 0.5.0+git.11.gbe6169e); however:
  Package sniproxy is not installed.

dpkg: error processing package sniproxy-dbg (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 sniproxy-dbg

**Comment by dlundquist** [comment]
`dpkg -i  .../sniproxy_0.5.0+git.11.gbe6169e_amd64.deb` should do it. You've tried to install the debug symbols package rather than the actual binary package.
