### ISSUE TITLE
SNI Proxy This procedure is multi-threaded?

### ISSUE THREAD

**Issue by sbwml** [dlundquist/sniproxy#253]
My use is through the SNI Proxy proxy network vps port, but I found that when the site traffic is relatively large, SNI Proxy performance seems to be very large decline, what is the way to improve the performance of SNI Proxy? Like nginx, multithreading work!

——From Google Chinese translation

我的配置是这样的：

user daemon
pidfile /tmp/webproxy.pid
listen 80 {
	proto http
	table http_hosts
}
listen 443 {
	proto tls
	table https_hosts
}
listen 8080 {
	proto http
	table http_8080
}

########### 内网代理 ############

table http_hosts {
	admin.domain.cn 127.0.0.1:5
    linux.domain.cn 172.20.10.84:80
	demo.domain.cn 172.20.10.101:8500
	pan.domain.cn 172.20.10.94:80
	apn.domain.cn 172.20.10.19:80
	apt.domain.cn 172.20.10.19:80
	www.domain.cn 172.20.10.19:80
	domain.cn 172.20.10.19:80
	help.domain.cn 172.20.10.19:80
	mirror.domain.cn 172.20.10.19:80
	mirrors.domain.cn 172.20.10.19:80
	ngrok.domain.cn 172.20.10.19:80
	blog.domain.cn 172.20.10.19:80
	down.domain.cn 172.20.10.19:80
	top.domain.cn 172.20.10.19:80
	amh.domain.cn 172.20.10.19:8888
}

table https_hosts {
	pan.domain.cn 172.20.10.94:443
    linux.domain.cn 172.20.10.84:443
	office.domain.cn 172.20.10.95:443
	apn.domain.cn 172.20.10.19:443
	www.domain.cn 172.20.10.19:443
	domain.cn 172.20.10.19:443
	help.domain.cn 172.20.10.19:443
	mirror.domain.cn 172.20.10.19:443
	mirrors.domain.cn 172.20.10.19:443
	ngrok.domain.cn 172.20.10.19:443
	blog.domain.cn 172.20.10.19:443
	down.domain.cn 172.20.10.19:443
	443.domain.cn 172.20.10.101:443
	top.domain.cn 172.20.10.19:443
	amh.domain.cn 172.20.10.19:9999
}

table http_8080 {
	.* 172.20.10.101:8080
}

**Comment by im8a** [comment]
You should increase open file limit on your Linux system. 
Usually, Linux's default is only 1024 and could be a bottleneck when the traffic grows. 
`ulimit -n `
tells your current open files limit
Refer to this guide to increase it permanently[https://ro-che.info/articles/2017-03-26-increase-open-files-limit](url).
I usually try to change the number to 65535 to ensure performance.

流量大的时候 > TCP连接多 > Linux默认 1024 open files 会成为瓶颈
具体参考上面英文详解

**Comment by sbwml** [comment]
非常感谢您提供的方法！
I do ulimit -n Linux acquiescence number is 1024, I am in accordance with the article you provide modified 65535, restart linux ulimit-n number is 65535.
——来自Google Translate.

echo "* - nofile 65535" >>/etc/security/limits.conf && reboot

[root@localhost ~]# ulimit -Sn
65535
[root@localhost ~]#

I have a high test on the site, the effect is much better than before!

谢谢！
