### ISSUE TITLE
3 FAILS during the installation

### ISSUE THREAD

**Issue by PantherJohn** [dlundquist/sniproxy#256]
FAIL: reload_test
FAIL: config_test
FAIL: bad_dns_request_test
...
What does it mean?

**Comment by JohnAndersonCA** [comment]
and after configuring "sniproxy.conf" the server refused to connect either at port 80 or port 443. What happened I just can't figure it out

**Comment by dlundquist** [comment]
That indicates that your build failed several tests that ship with the source. `config_test` is a bit alarming since this test simply parses the included sniproxy.conf file, so it's not surprising you can't connect if the build is unable to parse config files.

Could you provide a bit more information about your build environment: Distribution, architecture, versions, etc? Where there any compiler warnings during the build?

Also, it appears you are running a recent version of autotools there should be individual test result files in `tests/*.log`.

Many of the tests rely on local network connectivity and opening listening sockets on high TCP ports (8080-8083), do you have any firewall or other daemons running on your build machine which could interfere?

**Comment by JohnAndersonCA** [comment]
sniproxy-0.5.0-1.el7.centos.x86_64.rpm
I didn’t receive warnings however 

I installed Shadowsocks at the same time

**Comment by JohnAndersonCA** [comment]
But they didn’t supposingly share the same port

**Comment by JohnAndersonCA** [comment]
The log says it failed to parse the conf
Here is the system core version 

2.6.32-042stab123.3 x86_64 GNU/Linux
CentOS 7

**Comment by JohnAndersonCA** [comment]
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
...
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no

**Comment by JohnAndersonCA** [comment]
Now I fixed some of the problems and the config was successfully parsed.
but still the reload_test failed
it says "curl: (52) Empty reply from server
curl: (52) Empty reply from server
2017-10-14 03:43:05 recv(): Connection refused, closing connection
curl: (52) Empty reply from server"

**Comment by JohnAndersonCA** [comment]
#251

**Comment by JohnAndersonCA** [comment]
but I didn't even see sniproxy was running

**Comment by PantherJohn** [comment]
Alright I got a solution.
the failure of reload_test is because of “user daemon”. I need to rewrite the line as “user root”

**Comment by dlundquist** [comment]
@PantherJohn Thank you for tracking this down, I've opened a new issue #261 to cover the root problem.

**Comment by nexusofdoom** [comment]
having the same issue with ubuntu 16.04 and getting sniproxy installed.

**Comment by nexusofdoom** [comment]
==========================================================
   sniproxy 0.5.0+git.19.g7cbd992: tests/test-suite.log
==========================================================

# TOTAL: 20
# PASS:  18
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: config_test
=================

Failed to parse config
FAIL config_test (exit status: 1)

FAIL: bad_dns_request_test
==========================

2018-01-05 22:35:24 Only socket address backends are permitted when compiled without libudns
2018-01-05 22:35:24 error parsing /tmp/6FrC5qpuCG at 269 near:
2018-01-05 22:35:24 250

2018-01-05 22:35:24 258 table {

2018-01-05 22:35:24 270     .* *:80

2018-01-05 22:35:24 272 }

2018-01-05 22:35:24 272 (null)
Unable to load /tmp/6FrC5qpuCG
Usage: sniproxy [-c <config>] [-f] [-n <max file descriptor limit>] [-V]
couldn't connect Connection refused at ./bad_dns_request_test line 49.
couldn't connect Connection refused at ./bad_dns_request_test line 49.
couldn't connect Connection refused at ./bad_dns_request_test line 49.
Test failed.
worker failed with exit code 111
worker failed with exit code 111
server failed with exit code 1
worker failed with exit code 111
FAIL bad_dns_request_test (exit status: 1)

**Comment by dlundquist** [comment]
`Only socket address backends are permitted when compiled without libudns`

It looks like you don't have libudns-dev installed on your system so DNS related features are disabled and the tests related to these are failing. If you intend to proxy to anything besides an IP address or UNIX socket you will need to install libudns and re-run the configure script.
