### ISSUE TITLE
Override DNS Resolver in Config

### ISSUE THREAD

**Issue by tmajibon** [dlundquist/sniproxy#264]
It would be helpful if we could specify the DNS resolver to use in the config separately from the hosts DNS resolution.

**Comment by dlundquist** [comment]
This should do the trick:
```
resolver {
    nameserver 8.8.8.8
    nameserver 8.8.4.4
}
```

**Comment by tmajibon** [comment]
Sweet! I'll try it out later, that should do the trick.

Using this for some DNS based proxying (namely of package repos), and this'll let me cache http traffic while passing through ssl
