### ISSUE TITLE
unable to start on kvm vps

### ISSUE THREAD

**Issue by NutterChen** [dlundquist/sniproxy#265]
![tosolve](https://user-images.githubusercontent.com/32509481/33618130-a98c5620-da1c-11e7-8838-09902e36e333.jpg)

**Comment by dlundquist** [comment]
@NutterChen Is there anything in the log you have configured? Would you mind sharing your configuration? You might also try running sniproxy in foreground if you are not seeing anything in the logs, with `-f` flag.

**Comment by NutterChen** [comment]
![tosolve](https://user-images.githubusercontent.com/32509481/33620963-58c5d646-da24-11e7-8b2d-31bdb670a02c.jpg)
![1](https://user-images.githubusercontent.com/32509481/33620948-5199870a-da24-11e7-86dc-457f0d5b90e7.jpg)

**Comment by NutterChen** [comment]
![2](https://user-images.githubusercontent.com/32509481/33621059-96b5bafc-da24-11e7-8dac-84adb7f0d5a9.jpg)

**Comment by dlundquist** [comment]
Would you mind turning up the logging verbosity to debug:

```
error_log {
    # You will want to either use syslog or configure log rotate for this file in the long term
    # Ensure either sniproxy is running with privileges to create files in the log directory and
    # to the log file itself if it already exists, otherwise create a subdirectory with those permission
    # Your existing config is running as root, so this will not be a problem for now, but without log
    # rotation this may fill the drive
    filename /var/log/sniproxy.log
    priority debug
}
```

If you're still have problems, would you mind trying the master branch to see if it's something that has already been fixed.
