### ISSUE TITLE
Integer overflow while parsing TLS header

### ISSUE THREAD

**Issue by vikmik** [dlundquist/sniproxy#271]
Hi there!

After a bit of head-scratching, I believe I found an integer overflow issue in parse_tls_header:
https://github.com/dlundquist/sniproxy/blob/b4e83367d2de00c1c74facd0bcc6592d0a26a6ba/src/tls.c#L124
```
    /* TLS record length */
    len = ((size_t)data[3] << 8) +
        (size_t)data[4] + TLS_HEADER_LEN;
    data_len = MIN(data_len, len);
```

My compiler (gcc 4.8.5, on x84_64) is using signed chars which, when cast to size_t, end up making "len" a 2^64-ish value due to the wrap-around.

Then, the condition below always evaluates to true, which causes the TLS connection to be dropped by sniproxy, while the client waits for the server hello.
```
    /* Check we received entire TLS record length */
    if (data_len < len)
        return -1;
```

I was able to resolve my issue just by adding intermediate casts to unsigned char while computing len. However I don't particularly like that, as there are other places potentially vulnerable to the same problem. Using an explicit unsigned char type throughout the code seems better, or maybe using -funsigned-char ?

Cheers!

Victor

**Comment by dlundquist** [comment]
@vikmik Thank you for bringing this to my attention. I guess I put too much confidence in the test suite. I need to read up on why the cast from a signed char to an unsigned long was sign extending the 8-bit value and review that entire patch for similar issues.

Do you know which client was generating this TLS client hello, or perhaps have obtained one I can add to the test suite? I suspect the TLS record was 128-255 bytes long which resulted in the sign extended len value, but specific example would be great.

**Comment by vikmik** [comment]
@dlundquist No problems! Yes, the client hello was 223 bytes large in an attempt I did with curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5 - I've attached a wireshark dump of the relevant fields below
But really, all clients I tried (Google Chrome, Firefox, ...) were generating >=128 bytes hellos.

The signed -> unsigned cast is vaguely described in the standard - see ISO/IEC 9899:1999 6.2.5/9
> a result that cannot be represented by the resulting unsigned integer type is
> reduced modulo the number that is one greater than the largest value that can be
> represented by the resulting type

size_t is an unsigned 64 bit integer in my case, so a negative 8-bit value 'X' is reduced modulo 2^64, which is 2^64 - X

```
Secure Sockets Layer
    SSL Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 223
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 219
            Version: TLS 1.2 (0x0303)
            Random
                GMT Unix Time: Dec 25, 2017 02:26:08.000000000 MST
                Random Bytes: ed0061040ebf88712aa249e2fff7ba006f56c4c49eaadd28...
            Session ID Length: 0
            Cipher Suites Length: 110
            Cipher Suites (55 suites)
            Compression Methods Length: 1
            Compression Methods (1 method)
                Compression Method: null (0)
            Extensions Length: 68
            Extension: server_name
                Type: server_name (0x0000)
                Length: 15
                Server Name Indication extension
                    Server Name list length: 13
                    Server Name Type: host_name (0)
                    Server Name length: 10
                    Server Name: abcdef.ghi
            Extension: elliptic_curves
                Type: elliptic_curves (0x000a)
                Length: 8
                Elliptic Curves Length: 6
                Elliptic curves (3 curves)
                    Elliptic curve: secp256r1 (0x0017)
                    Elliptic curve: secp384r1 (0x0018)
                    Elliptic curve: secp521r1 (0x0019)
            Extension: ec_point_formats
                Type: ec_point_formats (0x000b)
                Length: 2
                EC point formats Length: 1
                Elliptic curves point formats (1)
                    EC point format: uncompressed (0)
            Extension: signature_algorithms
                Type: signature_algorithms (0x000d)
                Length: 14
                Signature Hash Algorithms Length: 12
                Signature Hash Algorithms (6 algorithms)
            Extension: status_request
                Type: status_request (0x0005)
                Length: 5
                Certificate Status Type: OCSP (1)
                Responder ID list Length: 0
                Request Extensions Length: 0
            Extension: signed_certificate_timestamp
                Type: signed_certificate_timestamp (0x0012)
                Length: 0
                Data (0 bytes)
```

Thanks!
Victor

**Comment by vikmik** [comment]
But since the signed-ness of a char is compiler-dependent, I'm not sure how that would fit in your test suite (unless you want to use different compiler flags for your tests). Using "-funsigned-char" would make the behavior consistent across all compilers, effectively removing this blind spot and increasing the confidence in the test suite

**Comment by oldium** [comment]
@vikmik Passing `-funsigned-char` will not fix the problem with signed/unsigned mismatch. When I see the original code:

`len = ((unsigned char)data[3] << 8) +
        (unsigned char)data[4] + TLS_HEADER_LEN;`

the problem is not with types of operands, but what the compiler does with them before doing the math. In this particular case the compiler converts operands to `int` and the result type is also `int`. The `int` result is then assigned to `size_t`, which is `unsigned`. See _Integer promotion_ feature of C/C++.

**Comment by vikmik** [comment]
@oldium You might be looking at the code after @dlundquist reverted the offending commit. The offending code was captured in my first post, but the link to the code points to HEAD, which doesn't have the bug anymore. The original code is at https://github.com/dlundquist/sniproxy/blob/b4e83367d2de00c1c74facd0bcc6592d0a26a6ba/src/tls.c#L124

-funsigned-char will make sure the promotion to size_t does not involve the signed->unsigned modulo computation that applies to integer promotions (the one I cited from the ISO/IEC 9899 above). And TLS_HEADER_LEN is cast to size_t before it's added to the other operands.

Running this piece of code with the 2 options speaks for itself:

```
$ cat test.c
#define TLS_HEADER_LEN 5

#include <stdio.h>

int main(void) {
    char data[] = {0, 0, 0, 0, 223};
    size_t len = ((size_t)data[3] << 8) + (size_t)data[4] + TLS_HEADER_LEN;
    printf("%zu\n", len);
    return 0;
}
$ gcc test.c -Wall -Wextra -std=c99 -o test
$ ./test
18446744073709551588
$ gcc test.c -funsigned-char -Wall -Wextra -std=c99 -o test
$ ./test
228
```

I'm not saying this is the best course of action, but this definitely solves this particular issue (and the similar ones introduced with the offending commit)

**Comment by vikmik** [comment]
I've updated the original post to point to the right commit. Sorry for the confusion :-)

**Comment by dlundquist** [comment]
@vikmik Would you mind testing the updated sign conversion branch (https://github.com/dlundquist/sniproxy/commit/dcea64c4b11e8a7d1eb4021932722256b43cf1a1)?

**Comment by vikmik** [comment]
Works like a charm. Thanks @dlundquist !

**Comment by oldium** [comment]
I made a code review of sign conversion branch and the changes looks good, @dlundquist 👍
