### ISSUE TITLE
Transparent Proxy Not Working

### ISSUE THREAD

**Issue by Jip-Hop** [dlundquist/sniproxy#274]
Very glad I came across SNI Proxy :) It's been so much easier to set up name-based proxying compared to Nginx or HAProxy.

However I've been unsuccessful at configuring transparent proxying. This is my config before setting up transparent proxying:
```
user daemon

pidfile /tmp/sniproxy.pid

error_log {
    syslog daemon
    priority notice
}

listen 80 {
    proto http
    table HostnamesTable

    access_log {
        filename /var/log/sniproxy/http_access.log
        priority notice
    }
}

listen 443 {
    proto tls
    table HostnamesTable

    access_log {
        filename /var/log/sniproxy/https_access.log
        priority notice
    }
}

table HostnamesTable {
    # If port is not specified the listener port will be used
    seafile1.example.com 10.0.0.2
    seafile2.example.com 10.0.0.3
}
```
This is working great. SNI Proxy is running on a VPS with LAN IP 10.0.0.1. I'm running Tinc VPN on the VPS to connect a machine with LAN IP 10.0.0.2. SNP Proxy routs requests for seafile1.example.com to this machine on 10.0.0.2. There I've got Seafile running behind Nginx as reverse proxy. SSL is terminated by Nginx.

When logging in to Seafile this ip is logged: 10.0.0.1. That's the IP address of the VPS running SNI Proxy. Based on the [transparent_proxy_test](https://github.com/dlundquist/sniproxy/blob/4f9e244a5a20045058a5b255d693de9b15e68b78/tests/transparent_proxy_test) and issue #262 and #228 I came up with this config:
```
user root

pidfile /tmp/sniproxy.pid

error_log {
    syslog daemon
    priority notice
}

listen 80 {
    proto http
    table HostnamesTable

    source client

    access_log {
        filename /var/log/sniproxy/http_access.log
        priority notice
    }
}

listen 443 {
    proto tls
    table HostnamesTable

    source client

    access_log {
        filename /var/log/sniproxy/https_access.log
        priority notice
    }
}

table HostnamesTable {
    # If port is not specified the listener port will be used
    seafile1.example.com 10.0.0.2
    seafile2.example.com 10.0.0.3
}
```
However the logs of Seafile still show 10.0.0.1. So transparent proxying doesn't work. I need this for Fail2Ban which is also installed on 10.0.0.2.

I can hardly find any documentation about transparent proxying with SNI Proxy. Is transparent proxying not supported in this configuration?

**Comment by tmajibon** [comment]
Sorry, this seams like a semantic issue.

This isn't what transparent proxying means.

When you proxy a request, transparent or not, it's going to come from the ip address of the proxy as that is the endpoint of the tcp stream as far as the server is concerned.

What makes a proxy transparent is what it appears like to the clients connections on the network. A transparent proxy is one that intercepts traffic on the network seamlessly. SNIProxy can be transparent as you can create a firewall rule to forward all 443 traffic through it and (reasonably) expect the traffic to proceed as normal.

As a personal example, redirect domain names to a server to use a port 80 nginx transparent caching proxy, and use SNIProxy to allow https connections to that domain to continue as normal.

Depending on how exactly Seafile logs addresses, this is a case for nginx as a proxy instead, namely because you can edit headers to pass the X-Forwarded-For header to Seafile. (X-Forwarded-For is a standard header used with http/s proxies to pass their client's ip address to the server)

SNIProxy is not able to do this because it would require terminating the ssl stream to be able to edit the contents.

**Comment by Jip-Hop** [comment]
Great to hear you understand what's going on :) I thought I knew what transparent proxying means, but clearly I didn't.

> Transparent proxies are considered transparent because the user isn’t aware of them. On the other hand, the servers hosting the service recognize that the proxied traffic is coming from a proxy and not directly from the user. - [maxcdn](https://www.maxcdn.com/one/visual-glossary/transparent-proxy/).

I thought however I'd be able to also make it transparent to the destination server (with Nginx and Seafile in my case) as well. Because of these lines in [sniproxy.conf](https://github.com/dlundquist/sniproxy/blob/master/sniproxy.conf).

```
    # Specify the source address for outgoing connections.
    #
    # Use "source client" to enable transparent proxy support. This requires
    # running sniproxy as root ("user root").
```

I thought perhaps it would be similar to this:

> HAProxy “hides” the client IP by its own one: this can be an issue in some cases.
Here comes the transparent proxy mode: HAProxy can be configured to spoof the client IP address when establishing the TCP connection to the server. That way, the server thinks the connection comes from the client directly (of course, the server must answer back to HAProxy and not to the client, otherwise it can’t work: the client will get an acknowledge from the server IP while it has established the connection on HAProxy‘s IP). - [HAProxy](https://www.haproxy.com/blog/howto-transparent-proxying-and-binding-with-haproxy-and-aloha-load-balancer/)

Seems like HAProxy uses a different definition of transparent proxy from the one above...

As mentioned I'd like to log the origin IP and I found it's possible with Nginx:

> On the end servers I added
> 
> server {
>   listen 443 ssl proxy_protocol;
>   ...
>   set_real_ip_from 10.0.0.201;
>   real_ip_header proxy_protocol;
>   proxy_set_header X-Real-IP $proxy_protocol_addr;
>   proxy_set_header X-Fowarded-For $proxy_protocol_addr;
>   ...
> }
> 
> and on the load balancer
> 
> server {
>   listen 443;
>   proxy_protocol on; # Make sure this is enabled
>   proxy_pass $backend_cluster_map;
>   ...
> }
> And the application now sees the client IP address not the load balancer's with SSL passthrough.

From: [NGINX IP Transparency on SSL Stream](https://serverfault.com/questions/870570/nginx-ip-transparency-on-ssl-stream).

And another more complex example here: [Nginx SSL vhosting using Server Name Indication](https://blog.le-vert.net/?p=224).

Is there a way to pass the origin IP down to my destination (Nginx in front of Seafile) from SNI Proxy with SSL Pass Through?

**Comment by Jip-Hop** [comment]
Now that I better understand what I'm looking for I think the question comes down to this:
Does SNI Proxy support the [PROXY protocol](https://www.nginx.com/resources/admin-guide/proxy-protocol/)?
>The PROXY protocol enables NGINX and NGINX Plus to receive client connection information passed through proxy servers and load balancers such as HAproxy and Amazon Elastic Load Balancer (ELB).

**Comment by Jip-Hop** [comment]
And the answer is: not yet. #171

**Comment by dlundquist** [comment]
@Jip-Hop actually, a more specific answer is really soon: https://github.com/dlundquist/sniproxy/compare/proxy-header

**Comment by Jip-Hop** [comment]
Wow great news! Looking forward to the next release 👍

**Comment by dlundquist** [comment]
@Jip-Hop If you are going to be using PROXY v1 header feature, then I would really appreciate testing and feedback _before_ I cut a release.

**Comment by Jip-Hop** [comment]
I'll try it out today. Anything specific I need to be looking out for? Installation is the same as when installing a release I assume.

**Comment by Jip-Hop** [comment]
I've installed the proxy-header branch. How do I enable the proxy header?

**Comment by dlundquist** [comment]
@Jip-Hop Add the `proxy` keyword after a table entry or the listener address. 

```
listen 443 {
    proto tls
    fallback unix:/var/run/https-wildcard.sock
}

table {
    ^example.overthere.org$ unix:/var/run/haproxy/https-radosgw.sock proxy
}
```

**Comment by Jip-Hop** [comment]
I think it works now!

```
user daemon

pidfile /tmp/sniproxy.pid

error_log {
    syslog daemon
    priority notice
}

listen 80 {
    proto http
    table HostnamesTable

    access_log {
        filename /var/log/sniproxy/http_access.log
        priority notice
    }
}

listen 443 {
    proto tls
    table HostnamesTable

    access_log {
        filename /var/log/sniproxy/https_access.log
        priority notice
    }
}

table HostnamesTable {
    # If port is not specified the listener port will be used
    seafile1.example.com 10.0.0.2 proxy
}
```

Default Seafile Nginx configuration (without support for Proxy Protocol):
```
server {
  listen       80;
  server_name  "";
  return 301 https://$http_host$request_uri;
}

server {
  listen 443;
  server_name  "";

  ssl on;
  ssl_certificate /etc/nginx/ssl/seafile.crt;
  ssl_certificate_key /etc/nginx/ssl/seafile.key;

  proxy_set_header X-Forwarded-For $remote_addr;

  location / {
    proxy_pass         http://127.0.0.1:8000;
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Host $server_name;
    proxy_read_timeout  1200s;

    # used for view/edit office file via Office Online Server
    client_max_body_size 0;

    access_log      /var/log/nginx/seahub.access.log;
    error_log       /var/log/nginx/seahub.error.log;
  }

  location /seafhttp {
    rewrite ^/seafhttp(.*)$ $1 break;
    proxy_pass http://127.0.0.1:8082;
    client_max_body_size 0;
    proxy_connect_timeout  36000s;
    proxy_read_timeout  36000s;
    proxy_send_timeout  36000s;
  }

  location /media {
    root /opt/seafile/seafile-server-latest/seahub;
  }

  location /seafdav {
    fastcgi_pass    127.0.0.1:8080;
    fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
    fastcgi_param   PATH_INFO           $fastcgi_script_name;
    fastcgi_param   SERVER_PROTOCOL     $server_protocol;
    fastcgi_param   QUERY_STRING        $query_string;
    fastcgi_param   REQUEST_METHOD      $request_method;
    fastcgi_param   CONTENT_TYPE        $content_type;
    fastcgi_param   CONTENT_LENGTH      $content_length;
    fastcgi_param   SERVER_ADDR         $server_addr;
    fastcgi_param   SERVER_PORT         $server_port;
    fastcgi_param   SERVER_NAME         $server_name;
    fastcgi_param   REMOTE_ADDR         $remote_addr;
    fastcgi_param   HTTPS               on;
    client_max_body_size 0;
    access_log      /var/log/nginx/seafdav.access.log;
    error_log       /var/log/nginx/seafdav.error.log;
  }
}
```
Changed this:
```
<   listen       80 proxy_protocol;
---
>   listen       80;
8c8
<   listen 443 proxy_protocol;
---
>   listen 443;
15,16d14
<   set_real_ip_from 10.0.0.1;
< 
18,19c16
<   real_ip_header proxy_protocol;
<   
---
> 
```

Working Nginx configuration:
```
server {
  listen       80 proxy_protocol;
  server_name  "";
  return 301 https://$http_host$request_uri;
}

server {
  listen 443 proxy_protocol;
  server_name  "";

  ssl on;
  ssl_certificate /etc/nginx/ssl/seafile.crt;
  ssl_certificate_key /etc/nginx/ssl/seafile.key;

  set_real_ip_from 10.0.0.1;

  proxy_set_header X-Forwarded-For $remote_addr;
  real_ip_header proxy_protocol;

  location / {
    proxy_pass         http://127.0.0.1:8000;
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Host $server_name;
    proxy_read_timeout  1200s;

    # used for view/edit office file via Office Online Server
    client_max_body_size 0;

    access_log      /var/log/nginx/seahub.access.log;
    error_log       /var/log/nginx/seahub.error.log;
  }

  location /seafhttp {
    rewrite ^/seafhttp(.*)$ $1 break;
    proxy_pass http://127.0.0.1:8082;
    client_max_body_size 0;
    proxy_connect_timeout  36000s;
    proxy_read_timeout  36000s;
    proxy_send_timeout  36000s;
  }

  location /media {
    root /opt/seafile/seafile-server-latest/seahub;
  }

  location /seafdav {
    fastcgi_pass    127.0.0.1:8080;
    fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
    fastcgi_param   PATH_INFO           $fastcgi_script_name;
    fastcgi_param   SERVER_PROTOCOL     $server_protocol;
    fastcgi_param   QUERY_STRING        $query_string;
    fastcgi_param   REQUEST_METHOD      $request_method;
    fastcgi_param   CONTENT_TYPE        $content_type;
    fastcgi_param   CONTENT_LENGTH      $content_length;
    fastcgi_param   SERVER_ADDR         $server_addr;
    fastcgi_param   SERVER_PORT         $server_port;
    fastcgi_param   SERVER_NAME         $server_name;
    fastcgi_param   REMOTE_ADDR         $remote_addr;
    fastcgi_param   HTTPS               on;
    client_max_body_size 0;
    access_log      /var/log/nginx/seafdav.access.log;
    error_log       /var/log/nginx/seafdav.error.log;
  }
}
```
The client IP addresses show up in my logs now... this is what I wanted :)

**Comment by bilogic** [comment]
```
table HostnamesTable {
    # If port is not specified the listener port will be used
    seafile1.example.com 10.0.0.2 proxy
}
```

I compiled from the source, but it can't accept the additional `proxy` at the end of the line, kept saying `Unable to load /etc/sniproxy.conf`

Any ideas?
