### ISSUE TITLE
unsafe stripping of port from hostname in http.c (incompatibility with IPv6)

### ISSUE THREAD

**Issue by starter48** [dlundquist/sniproxy#279]
The **parse_http_header()** function in **http.c** corrupts hostname while stripping port from,
if hostname is an IPv6 address without a port.
For example, the hostname of the following header
**Host: [2001:1122::3344]**
will be trimmed to **[2001:1122:** because **parse_http_header()** trim it simple by the last colon.
This is the loop (original code) that strip a port portion:
```
    for (i = result - 1; i >= 0; i--)
        if ((*hostname)[i] == ':') {
            (*hostname)[i] = '\0';
            result = i;
            break;
}
```
I suggest to add a check for ']' to the loop,
to stop the loop if trailing ']' of IPv6 found:
```
    for (i = result - 1; i >= 0 && (*hostname)[i] != ']'; i--)
```

**Comment by dlundquist** [comment]
Thank you for pointing this out! Using wild card table targets with IP address literals is disallowed in listener_lookup_server_address() to prevent a recursive proxying DoS and accessing internal services.

**Comment by starter48** [comment]
I've encountered [this problem here](https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/http.c) (not your repo). People borrowed your code but it seems not very suitable for reuse. I suggest to make a comment about incompatibility with pure IPv6 addresses if you don't plan to improve your code.

**Comment by dlundquist** [comment]
I do intend to fix this, but only so the parser is correct and the error
messages more clear.

-Dustin
