### ISSUE TITLE
What are the priority levels?

### ISSUE THREAD

**Issue by stampycode** [dlundquist/sniproxy#282]
There's nothing to suggest we can use anything other than 'notice' for the priority field, can you provide a list? I tried 'debug' and broke it...

**Comment by dlundquist** [comment]
These are the standard syslog priorities: `emergency`, `alert`, `critical`, `error`, `warning`, `notice`, `info`, and `debug`. They are defined https://github.com/dlundquist/sniproxy/blob/master/src/config.c#L460-L472

Thank you for pointing out these are not documented in the `sniproxy.conf.5`.

What do you mean by breaking?
