### ISSUE TITLE
Ubuntu 18.04.1

### ISSUE THREAD

**Issue by mrahmadt** [dlundquist/sniproxy#303]
Hello

I'm trying to install sniproxy on Ubuntu 18.04.1 but I'm getting this error

`
 root@proxy:~# sudo apt-get install autotools-dev cdbs debhelper dh-autoreconf dpkg-dev gettext libev-dev libpcre3-dev libudns-dev pkg-config fakeroot devscripts
 Reading package lists... Done
 Building dependency tree
 Reading state information... Done
 Package cdbs is not available, but is referred to by another package.
 This may mean that the package is missing, has been obsoleted, or
 is only available from another source
 
 E: Package 'cdbs' has no installation candidate
 E: Unable to locate package libev-dev
 E: Unable to locate package libudns-dev
`

Any help?

**Comment by dlundquist** [comment]
SNIproxy is included in Ubuntu 18.04 in the "unviverse" section of the
Ubuntu repository. Missing the "universe" section in your apt sources might
be the cause of the other missing packages. If you want built sniproxy from
source, I would suggest starting with `apt-get build-dep sniproxy`.


-Dustin

**Comment by mrahmadt** [comment]
Thanks

I managed to install it after enabling unviverse  repository

`sudo add-apt-repository universe`
