### ISSUE TITLE
How to start service of ubuntu package

### ISSUE THREAD

**Issue by CptLeeChuck** [dlundquist/sniproxy#306]
Hi,

I installed sniproxy on Ubuntu 18.04 with:
`apt-get install sniproxy`
it installs libev4, libudns0 and sniproxy_0.5.0-2_amd64.

However, the service does not start with system boot. Also manual starting fails withot error message. After
`service sniproxy start`
neither "netstat -tlanp" shows the port listening, nor htop shows a task running.
More strange "service --status-all" shows it now as running, what is not the case.

The config file seems to be fine, as when I run "sniproxy -f" manually, it's listening as expected:

`
tcp        0      0 123.123.123.123:443      0.0.0.0:*               LISTEN      6363/sniproxy
`
`
tcp6       0      0 2aaa:bbbb:4444:c666::443 :::*                    LISTEN      6363/sniproxy       
`

and htop shows two tasks, one running as daemon and one as root, and the proxy works as expected, all configured traffic is proxied. But I'm lost how to get this configured as service.

What could be wrong with the service setup? I would like this to run it automatically after every boot.

**Comment by dlundquist** [comment]
Did you enable it in /etc/default/sniproxy? It is disabled by default so
not to conflict with another web server running in the system.

**Comment by CptLeeChuck** [comment]
Oh, thanks so much, I spent already 2 hours, but the solution was so simple, should have asked earlier :-)

**Comment by abliss** [comment]
Maybe it'd be worth notiing this  in /etc/sniproxy.conf ?
