### ISSUE TITLE
DNS port

### ISSUE THREAD

**Issue by mrahmadt** [dlundquist/sniproxy#309]
Hello

Is there anyway I can he DNS port ?

And how I can force sniproxy to use the nameservers in sniproxy.conf and never use there local dns?

**Comment by dlundquist** [comment]
I think Libudns has a knob for this, but your better off running a local
caching resolver configured to forward queries on a specific port (or
better yet over IPSec/DTLS). I would look at the code to configure
nameservers and libudns docs if you want to go the route of not running a
local resolver.

-Dustin

**Comment by mrahmadt** [comment]
I think I will go with your advice and running a local caching resolver (dnsmasq)

Thanks
