### ISSUE TITLE
Improve performance by adding multiple instance listening on multiple IPs - Not an issue 

### ISSUE THREAD

**Issue by charithaka1990** [dlundquist/sniproxy#310]
I'm using sniproxy for one of our project and I'm impressed with the performance and reliability. I'm running on  debian and cenots both rock solid and do the work without any issue. I have small question since I'm planing to adding load balancing to my architecture . I choose Nginx tcp module for load balancing. In my current boxes  I have multiple IP's configured  and I have single sni process which have multiple listeners to listen all the available IP address. My question is if I add multiple SNI instances  with listeners on it to listen all the available IP address  is it possible to improve the performance ? And how it will help to Nginx based tcp load-balancing rather than having single process of sniproxy

**Comment by PantherJohn** [comment]
Probably you should consider enabling TCP port reuse in your `listening` blocks.
```
 # Enable SO_REUSEPORT to allow multiple processes to bind to this ip:port pair
 reuseport yes
```

**Comment by gun1x** [comment]
If you have 1000 IPs, is it better to run sniproxy 1000 times, or to create 1000 listeners?
