### ISSUE TITLE
Can proxy ssh? If can proxy ssh, how do configure it?

### ISSUE THREAD

**Issue by richfang** [dlundquist/sniproxy#311]
Can proxy ssh? If can proxy ssh, how do configure it?

**Comment by dlundquist** [comment]
Unfortunately SSH doesn’t include the host name in plain text form anywhere in the initial handshake, so the approach used by SNIproxy doesn’t apply. I would suggest either multiple destination NATs mapping each backend server to a distinct TCP port or a bounce/bastion host which users can’t SSH into and then from there connect to the selected backend server either using SSH agent forwarding or netcat in conjunction with the OpenSSH proxy command.
