### ISSUE TITLE
Netflix unblocker or proxy error

### ISSUE THREAD

**Issue by Sham-N** [dlundquist/sniproxy#324]
Hey,
While using sniproxy I'm getting the following err:
"Stream Error
You seem to be using an unblocker or proxy. Please turn off any of these services and try again. For more help, visit netflix.com/proxy."

Any ideas how can I fix that ?

Thanks Mr.Shamen

**Comment by dlundquist** [comment]
@Sham-N It sounds like Netflix is using some technical measures to block geo-IP-fencing circumvention, they appear to have a page describing there policies. As I've said before in other issues, I don't support using SNIproxy to circumvent GeoIP restrictions. I developed this software for another purpose, but if it works for you more power to you. If you find a but with SNIproxy itself, feel free to report it. Thanks.
