### ISSUE TITLE
Alpine Linux packages - sniproxy

### ISSUE THREAD

**Issue by huangsen365** [dlundquist/sniproxy#326]
Hi Team,

Is it safety to use Alpine Linux packages - sniproxy ?
Please refer to below screenshot/link,
https://pkgs.alpinelinux.org/package/edge/community/x86_64/sniproxy
![sniproxy](https://user-images.githubusercontent.com/1982355/53141928-fd40e580-35cc-11e9-9034-8969fa3e8f6c.PNG)

**Comment by dlundquist** [comment]
I don't maintain the Alpine packages, so I can't personally attest to their integrity. That being said, Alpine Linux is a reasonably widely use distribution and using a package from a distribution you already trust is a good bet, this package appears to be built from the recent 0.6.0 release tag. I've downloaded the tarball and verified the sha512 checksum which the Alpine package is built from.

**Comment by huangsen365** [comment]
Thanks Dustin!
I am using this package now, it is very easy to use, and it is stable.

Because I am searching the docker image and found the package being as a practice here https://hub.docker.com/r/steamcache/sniproxy/dockerfile

I only take 5 minutes to complete the deployment.

You know, in China, there are a lot of users are using docker for the projects.
And SNIProxy has become more and more popular.

Considering this, would you think about to see if it is possible to add new installation approaches such as above ?

Thanks again!
