### ISSUE TITLE
Nginx sniproxy ?

### ISSUE THREAD

**Issue by huangsen365** [dlundquist/sniproxy#327]
Hi Team,

It looks like that nginx already has the similar function to support SNI proxy? If yes, then what the meaningful for this project? Is there any advantage for using sniproxy? Any difference?
**  stream {
    server {
        listen 443;
        ssl_preread on;
        resolver 8.8.8.8;
        proxy_pass $ssl_preread_server_name:443;
    }
}
  **

Please refer to http://nginx.org/en/docs/stream/ngx_stream_ssl_preread_module.html
![nginx_sni_proxy](https://user-images.githubusercontent.com/1982355/53189587-d7562800-3642-11e9-909b-4dc584afe081.png)

Thanks and Regards,

**Comment by dlundquist** [comment]
Prior to staring inn SNIproxy the surveyed existing web proxies including Nginx and none of them supported proxying based on the SNI extension contents at that time. Now, at least Nginx supports this although last time I tried it was restricted to the stream proxy mode and one could mix SNI stream forwarding with TLS termination on the same listener. Now, I would say whichever program better fits your needs. SNIproxy is a significantly smaller code base while Nginx’s multithreaded model would preform better on a multi core box.
