### ISSUE TITLE
sniproxy in front of apache with proxy_protocol

### ISSUE THREAD

**Issue by basti12203** [dlundquist/sniproxy#334]
hello,
I use sniproxy in front of nginx and apache with proxy_protocol. nginx is working fine.
As I can see in the logs the "real" IP address of the client is convert to IPv6 and sent to backend.
`[::ffff:192.168.0.1]:44666 -> [::ffff:192.168.0.136]:80 -> 10.0.0.5:80 [www.example.com] 0/0 bytes tx 818/818 bytes rx 0.002 seconds`

This seems to be a Problem for the RemoteIPProxyProtocol  in remoteip module of apache.
access.log:
`192.168.122.1 - - [21/Jun/2019:20:14:36 +0200] "PROXY TCP6 ::ffff:192.168.0.1" 400 0 "-" "-"
`
error.log:
`[Fri Jun 21 20:32:53.350531 2019] [remoteip:error] [pid 563] [client 192.168.122.1:44614] AH03500: RemoteIPProxyProtocol: invalid client-address '::ffff:192.168.0.1' found in header 'PROXY TCP6 ::ffff:192.168.0.1 ::ffff:192.168.0.136 44666 80'`
Without proxy_protocol is works. 
I have also try resolver with mode ipv4_only with the same result.

**Comment by dlundquist** [comment]
Try changing your listen directive to listen 0.0.0.0:443, so sniproxy isn’t receiving incoming connections on a dual stack socket. If that doesn’t fix it, I can take a look at the proxy header insertion and insert it as IPv4 if both addresses are IPv6 mapped IPv4 addresses.

**Comment by basti12203** [comment]
thank you for the fast answer.
listen on ipv4 only fix it at the moment. but i think it would be better to have a config switch or something else, to send ipv4 to the backend.
so it would be possible to get ipv6 requests on the proxy and send it as ipv4 to the backend.

**Comment by dlundquist** [comment]
Two listeners one for ipv4 and one for ipv6 with the ipv6_only flag will do that, they can both use the same table and connect to ipv4 backends. insert_proxy_v1_header() could be updated to insert and IPv4 proxy header in the IPv6 mapped IPv4 case, but that seems like a low priority. Your welcome to take a stab at it.

**Comment by bilogic** [comment]
```
[2024-10-14 13:47:00.711407] [remoteip:error] [C:6peYXVEDKDQ] AH03500: RemoteIPProxyProtocol: invalid client-address '::ffff:192.168.1.2' found in header 'PROXY TCP6 ::ffff:192.168.1.2 ::ffff:192.168.1.3 4134 443'
```
I have the above error because of appending `proxy_protocol` to 1 of my host in `sniproxy.conf`
Also modified to `listen 0.0.0.0:443 {`, but that ended up causing nothing to route (including those domains without proxy_protocol)

Any ideas?
