### ISSUE TITLE
Build failed in Archlinux

### ISSUE THREAD

**Issue by kkkgo** [dlundquist/sniproxy#339]
./autogen.sh  
./setver.sh: line 35: debchange: command not found  
configure.ac:20: error: possibly undefined macro: AC_LIB_HAVE_LINKFLAGS  
      If this token and others are legitimate, please use m4_pattern_allow.  
      See the Autoconf documentation.  
configure.ac:22: error: possibly undefined macro: AC_SUBST  
configure.ac:24: error: possibly undefined macro: AC_MSG_ERROR  
configure.ac:47: error: possibly undefined macro: AS_IF  
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by kkkgo** [comment]
./configure   
checking for a BSD-compatible install... /usr/bin/install -c  
checking whether build environment is sane... yes    
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p  
checking for gawk... gawk  
checking whether make sets $(MAKE)... yes  
checking whether make supports nested variables... yes  
checking whether make supports nested variables... (cached) yes  
checking whether make supports the include directive... yes (GNU style)  
checking for gcc... gcc  
checking whether the C compiler works... yes  
checking for C compiler default output file name... a.out  
checking for suffix of executables...  
checking whether we are cross compiling... no  
checking for suffix of object files... o  
checking whether we are using the GNU C compiler... yes  
checking whether gcc accepts -g... yes  
checking for gcc option to accept ISO C89... none needed  
checking whether gcc understands -c and -o together... yes  
checking dependency style of gcc... gcc3  
checking how to run the C preprocessor... gcc -E  
checking for grep that handles long lines and -e... /usr/bin/grep  
checking for egrep... /usr/bin/grep -E  
checking for ANSI C header files... yes  
checking for sys/types.h... yes  
checking for sys/stat.h... yes  
checking for stdlib.h... yes  
checking for string.h... yes  
checking for memory.h... yes  
checking for strings.h... yes  
checking for inttypes.h... yes  
checking for stdint.h... yes  
checking for unistd.h... yes  
checking minix/config.h usability... no  
checking minix/config.h presence... no  
checking for minix/config.h... no   
checking whether it is safe to define __EXTENSIONS__... yes  
checking for gcc option to accept ISO C99... none needed  
**./configure: line 4553: syntax error near unexpected token `LIBEV,'  
./configure: line 4553: `PKG_CHECK_MODULES(LIBEV, libev, HAVE_LIBEV=yes; $as_echo "#define   
 HAVE_LIBEV 1" >>confdefs.h'**

**Comment by Hollish** [comment]
Not to necro this issue, but I'm getting the same errors in RHEL 7. I've been hacking away at this for a while and can't seem to find a solution.
