### ISSUE TITLE
Libev4 not found 13.1 x32

### ISSUE THREAD

**Issue by mikefallen1** [dlundquist/sniproxy#35]
When i try to compile i keep getting  

root@carbon:/home/sniproxy-master# ./autogen.sh && ./configure && make check &&                                         sudo make install
configure.ac:7: installing `./install-sh'
configure.ac:7: installing`./missing'
src/Makefile.am: installing `./depcomp'
Makefile.am: installing`./INSTALL'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... no
checking for style of include used by make... none
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... none
checking for gcc option to accept ISO C99... -std=gnu99
checking for library containing ev_run... no
configure: error: libev4 not found

But it is installed as you can see here? 

root@carbon:/home/sniproxy-master# dpkg -l libev4
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                Version        Architecture   Description
+++-===================-==============-==============-===========================================
ii  libev4              1:4.11-1       i386           high-performance event loop library modelle

**Comment by zhuleipd** [comment]
yum install libev-devel
