### ISSUE TITLE
Process Line Feed in next_header function

### ISSUE THREAD

**Issue by choupani** [dlundquist/sniproxy#366]
next_header() function only can process \r\n pairs, but according the RFC, HTTP header can have only \n.

GET / HTTP/1.1\n
Host: aaa.aaa\n
\n

**Comment by oldium** [comment]
Which RFC are you referring to? [RFC 2616](https://tools.ietf.org/html/rfc2616) states"

```
        generic-message = start-line
                          *(message-header CRLF)
                          CRLF
                          [ message-body ]
        start-line      = Request-Line | Status-Line
        Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
```

CRLF is CR followed by LF, so \r\n.

**Comment by choupani** [comment]
RFC 2616 - Section 19.3 .
The line terminator for message-header fields is the sequence CRLF.
However, we recommend that applications, when parsing such headers, 
recognise a single LF as a line terminator and ignore the leading CR.

If you don't believe, send the http-req with LF to the web server and see the response.

**Comment by choupani** [comment]
Use this trick to bypass censorship, If they have this hole.

**Comment by oldium** [comment]
Correct, RFC (also newer RFC 7230) recommends to be fault tolerant whenever it is unambiguous. This feature is completely optional, though.

**Comment by oldium** [comment]
I have just created a pull request to add LF handling. Hopefully @dlundquist gets some time to process it.
