### ISSUE TITLE
Clarify new upstream?

### ISSUE THREAD

**Issue by womfoo** [dlundquist/sniproxy#379]
There is another fork at [renaudallard/sniproxy](https://github.com/renaudallard/sniproxy) with multiple releases up to 0.6.5 over the past year.

The fork in question is used by OpenBSD but it is not clear if this is official.

**Comment by renaudallard** [comment]
It is a fork mostly dedicated to OpenBSD. I have included some improvements which have been suggested on this repo but never committed, and there are also some security related modifications which are only supported on OpenBSD. It is easier and more readable to include it into a specific fork than putting all the patches directly into the OpenBSD ports system. That said, it should work under other OSes, but I have not tried.
So, from the point of view of dlundquist, it's not official.

**Comment by womfoo** [comment]
Thanks for clearing this up @renaudallard. Now closing this case.
