### ISSUE TITLE
pcre library is obsolete, please consider to switch to pcre2

### ISSUE THREAD

**Issue by david-geiger** [dlundquist/sniproxy#392]
The PCRE library is now abandoned and not maintained anymore. That library should not be used, especially when the input can come from an untrusted source.

There is a newer library implemented (pcre2), which should be used instead (documentation is here: https://pcre.org/current/doc/html/

And also Mageia Linux planned to drop old pcre library like some others distributions.

Regards,
David

**Comment by loqs** [comment]
@david-geiger does https://gist.github.com/loqs/22fe9db0bb92f0a85da2fbfa86dadeb2 work for you?

**Comment by david-geiger** [comment]
@loqs yes it compile fine and work.

**Comment by dvzrv** [comment]
Hi! :wave: 

We are currently looking into [moving packages from pcre to pcre2 on Arch Linux](https://archlinux.org/todo/move-to-pcre2/).
We would therefore also be very interested in seeing a port of this project to pcre2! :)

@loqs could you create a pull request for that?

**Comment by renaudallard** [comment]
> @david-geiger does https://gist.github.com/loqs/22fe9db0bb92f0a85da2fbfa86dadeb2 work for you?

Didn't you have issues? I tried the patch. It compiles fine, sniproxy starts, but fails forwarding to the correct server.

**Comment by loqs** [comment]
@renaudallard any ideas on what the issue with the change to PCRE 2 could be?

**Comment by renaudallard** [comment]
Unfortunately, I tried on machines that were more or less in production, so I could not check fore very long. In the logs, sniproxy wrote the correct forwarding, but, on the client side, the connection closed instantly.

**Comment by loqs** [comment]
Please see the change I made in [df4a34e1debfddddc14f1e71709ea3a71ce643f5](https://github.com/dlundquist/sniproxy/compare/aa2e5eed07917703150a534011fc0e34fe182ee9..df4a34e1debfddddc14f1e71709ea3a71ce643f5).  I hope that fixes the issue.

**Comment by renaudallard** [comment]
With that patch, the error is different, but it still doesn't work properly.

With firefox, I get:

`
Secure Connection Failed

An error occurred during a connection to sub.domain.tld. Cannot communicate securely with peer: no common encryption algorithm(s).

Error code: SSL_ERROR_NO_CYPHER_OVERLAP`

**Comment by dlundquist** [comment]
Done: 7fdd86c0.
