### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by stokito** [dlundquist/sniproxy#393]
It would be useful to add alternatives to a README with a short description of key differences. Here what I found:
* https://github.com/yrutschle/sslh has OpenWrt and Ubuntu packages
* https://github.com/Intika-Linux-Proxy/SNI-SSL-Proxy
* https://github.com/0x7a657573/zroxy
* https://github.com/topics/tls-proxy?l=c&o=desc&s=stars some others but they are mostly full TLS proxies

**Comment by dlundquist** [comment]
Thanks for the analysis. I would encourage you to publish it on blog or wiki, but I’m not going to endorse other projects (with the exception of dependencies) here in this repo.

**Comment by stokito** [comment]
thank you for the response. It was not about endorsement but to show a difference to help to choose. Anyway thank you for the response.

**Comment by spacesynth** [comment]
```git clone https://github.com/inetaf/tcpproxy
cd tcpproxy/cmd/tlsrouter
go build .```
1232 Stars, 1 dependency, confirmed working, very easy config


https://github.com/atenart/sniproxy
24 stars, 0 dependencies, confirmed working, also easy config
