### ISSUE TITLE
ability to use github actions

### ISSUE THREAD

**Issue by saman3d** [dlundquist/sniproxy#396]
github actions gives the project ability to manage CI/CD pipelines seamlessly since its a native feature of github itself. meaning project can manage code, pull requests, CI/CD pipelines all in one place.
right now the project is using tavis ci to do some tests on every commit. we can now migrate testing to github actions and use some external features like automating releases(if the project plans to do so), and building and pushing images directly to github packages itself (ghcr.io).

**Comment by dlundquist** [comment]
I'm aware of the new GitHub feature, but is it really an issue to make suggest migrating CI environments?

**Comment by saman3d** [comment]
one thing that i think is unplanned in this project is ease of use.
