### ISSUE TITLE
[Urgent] how can I fix this? Package sniproxy is not installed for 0.6.1

### ISSUE THREAD

**Issue by Tushar5525** [dlundquist/sniproxy#397]
sudo dpkg -i ../sniproxy-dbg_0.6.1_amd64.deb
Selecting previously unselected package sniproxy-dbg.
(Reading database ... 81614 files and directories currently installed.)
Preparing to unpack .../sniproxy-dbg_0.6.1_amd64.deb ...
Unpacking sniproxy-dbg (0.6.1) ...
dpkg: dependency problems prevent configuration of sniproxy-dbg:
sniproxy-dbg depends on sniproxy (= 0.6.1); however:
Package sniproxy is not installed.

dpkg: error processing package sniproxy-dbg (--install):
dependency problems - leaving unconfigured
Errors were encountered while processing:
sniproxy-dbg

**Comment by dlundquist** [comment]
Looks like you attempted to install the debug symbols package without installing the sniproxy binary package. Either install the binary package (not named -dbg) or install from an apt repo.-DustinOn Jul 27, 2023, at 14:37, Tushar5525 ***@***.***> wrote:﻿
sudo dpkg -i ../sniproxy-dbg_0.6.1_amd64.deb
Selecting previously unselected package sniproxy-dbg.
(Reading database ... 81614 files and directories currently installed.)
Preparing to unpack .../sniproxy-dbg_0.6.1_amd64.deb ...
Unpacking sniproxy-dbg (0.6.1) ...
dpkg: dependency problems prevent configuration of sniproxy-dbg:
sniproxy-dbg depends on sniproxy (= 0.6.1); however:
Package sniproxy is not installed.
dpkg: error processing package sniproxy-dbg (--install):
dependency problems - leaving unconfigured
Errors were encountered while processing:
sniproxy-dbg

**Comment by Tushar5525** [comment]
Hi @dlundquist  Thank You so much for your response, could you please share the installation steps.

What I have followed, please find the below steps
   1  sudo apt update
    2  sudo apt upgrade
    3  sudo apt-get install autotools-dev cdbs debhelper dh-autoreconf dpkg-dev gettext libev-dev libpcre3-dev libudns-dev pkg-config fa
keroot devscripts
    4  git clone https://github.com/dlundquist/sniproxy.git
    5  ls -lrt
    6  cd sniproxy/
    7  ls -lrt
    8  ./autogen.sh && dpkg-buildpackage
    9  sudo dpkg -i ../sniproxy-dbg_0.6.1_amd64.deb


But I need something like below for 0.6.1, which package will support for this ?

sudo dpkg -i **../sniproxy_0.6.0+git.10.g822bb80_amd64.deb**

**Comment by Tushar5525** [comment]
Hi @dlundquist  Could you please respond as we are not able to find the location of the debian package ?

**Comment by dlundquist** [comment]
`dpkg-buildpackage` produces multiple files one of them is the debug symbols package `sniproxy-dbg` the other is the binary package `sniproxy`. The version in the package is obtained from `git describe`, so it looks like built from multiple git commits.  I would suggest reading the `dpkg-buildpackage` output to see which files are generated. You will want to install the package that begins with `sniproxy_` (the binary package) rather than `sniproxy-dbg_` (the debug symbols).
