### ISSUE TITLE
Reload config without restart sniproxy

### ISSUE THREAD

**Issue by avdhoot** [dlundquist/sniproxy#97]
Is it possibele to reload config without restart?

**Comment by CumpsD** [comment]
Am I correct that a sighup should now reload the config, with the code from #106?

**Comment by dlundquist** [comment]
@CumpsD Correct, sniproxy now reloads nearly all of the configuration upon receiving SIGHUP without terminating existing connections. I say nearly all because some configuration parameters are global for the life of the running process like the user and pid file location.

**Comment by CumpsD** [comment]
@dlundquist awesome! :+1: playing with setting up docker-gen with sniproxy to auto-reload when docker containers get started :)
